### ISSUE TITLE
Multiple fields in "type-of-asset" in /planning-options response should not be on type level

### ISSUE THREAD

**Issue by dejelger** [TOMP-WG/TOMP-API#105]
TOMP 1.2 (same goes for 1.1.1)

In the response of the `POST /planning-options` endpoint there is an array `results` with possible `type-of-asset` object. 
In the `type-of-asset`-object there are a number of field that should not be part of the type of an asset, but instead they should be part of the asset-object itself. 

This definitely applies to the `colour` and `state-of-charge` fields. 
Maybe some other fields too, like: `gears`, `infant-seat`, `travel-abroad`, `building-year`
For each field in `type-of-asset` it should be made clear whether it is part of identifying that type. 

An example:
There is a (electric-) bikestation with 5 available pedelecs (of exactly the same type), and this will be returned as 1 `type-of-asset` in a `POST /planning-options` data request. Each pedelec has its own `state-of-charg`', so how should this be used with regards to an asset-type?

**Comment by edwinvandenbelt** [comment]
Maybe an idea: move most of the fields from asset to asset-type and make asset a subclass of asset-type. In the array that is contained in the asset-type (containing physical assets) we can override the property value of the asset-type.

It makes it easy to have a asset-type 'LUXURIOUS' with all the same cars, but one of them has a child seat.
<pre>{ "name": "LUXURIOUS", ...
   "infant-seat": false, ....
   "assets": [ { .... "infant-seat": true, ... } ] .... }</pre>

**Comment by pimmeh** [comment]
Sounds good. :)

**Comment by dejelger** [comment]
That's a great idea. 
But an important note: Technically this possibly leads to unnecessary complex asset-types when an  asset-type will contain lots of different assets, each overriding a specific (different) property.

**Comment by edwinvandenbelt** [comment]
Yes, but the alternative is to create a type for every asset... And that's not really a good idea.... I want to facilitate only the 'normal' way of thinking: we group assets also on the majority of their properties (like 'old yellow bikes') and if all of them are produced in 2002, but some of them in 2003, it's convenient to make a type with 'building-year': 2002 and within the array the divergent assets with 'building-year': 2003.

**Comment by edwinvandenbelt** [comment]
in hotfix
