### ISSUE TITLE
Use Git Flow for changes to the API

### ISSUE THREAD

**Issue by Threore** [TOMP-WG/TOMP-API#109]
As part of the improved versioning and use of git's features, we should also make better and more consistent use of branches. I suggest we use a variant of the ubiquitous Git Flow style of doing branches. Concretely, this means:

- the `master` branch is **only** used for release commits (so v1.2 -> v.1.2.1 -> v1.3 -> v2.0 etc.)
- `develop` branches (here two, for the next major and minor releases) is used for incremental changes
- when a develop version is ready for release, it briefly goes into a `release-v.x.x.x` branch to make the last few changes and bug fixes before being merged into master with the next version number
- bigger changes that need a lot of work happen in `feature/<x>` branches that branch off from develop and are merged back into it when completed
- if a bug needs a quick fix, a `hotfix` branch can be made branching from a release in master and be merged back into it with a version bump

Git Flow is the most common organisation of branches used among projects that have any such organisation. It is completely compatible and even symbiotic with the other development practices we intend to adopt like semantic versioning #102 and releases using tags #107. Since it is about how we use branches I cannot put this change in a PR, so I'll create the branches already to show how it'd work. This is non-destructive so we can revert to the current practice if we do not approve.

See [https://nvie.com/posts/a-successful-git-branching-model/](https://nvie.com/posts/a-successful-git-branching-model/) for the Git Flow specification.

**Comment by Threore** [comment]
For an example, see commit 687166c in the `develop-major` branch. It fixes issue #95 which is a breaking change, so it is in the develop branch for the next major version. It is a small change, so it is in a single commit to that branch and not in a long-lived feature branch.

Because it is a breaking change it cannot be merged into master until we change to version 2.0 as per semantic versioning (#102). Unlike when we'd only have a master branch though, we can add this fix, a v2.0 change, and close issue #95 while still also working on version 1.3 in the `develop-minor` branch, and all the while leaving the master branch at 1.2 so that anyone landing on our GitHub page sees the code for the latest release without having to dig through previous commits to find it.

**Comment by edwinvandenbelt** [comment]
Good work! I was thinking in the same direction. I'm a starting github user. Can you write a small piece of text on the wiki how we want you to contribute using this structure? Btw what software do you use? Sourcetree? Or command line?

**Comment by Threore** [comment]
Yes I'll do that.

I mostly use command line myself, but something like SourceTree is easier if you're new to it. The visual layout of branches helps with understanding how they work.

**Comment by edwinvandenbelt** [comment]
Hmm, I'm thinking about the major and minor... Do we have to commit/merge all small changes to both branches?

**Comment by edwinvandenbelt** [comment]
Isn't it enough to have a master branche and a development brance? In the develop we can merge all forks of seperate developers during the bi-weekly sessions. Between 2 versions (1.2 -> 1.3) we can pile up all the changes for 1.3 in the development branche. During the period we can still change from 'minor' (1.2->1.3) to 'major' (1.2->2.0) until we merge it into the master. I can imagine we postpone the merge from forks that contain breaking changes until the last possible moment before releasing a 1.3 or 2.0.

**Comment by Threore** [comment]
I've created a page on the wiki: [How to contribute code](https://github.com/TOMP-WG/TOMP-API/wiki/How-to-contribute-code)

**Comment by edwinvandenbelt** [comment]
How can I comment?

**Comment by edwinvandenbelt** [comment]
Nice piece of work! I still have some comments.
a) merging is only done during the bi-weekly meetings
b) I think the setup is too complex. Feature branches are nice, but I think it will explode into a lot of PRs. Who's going to keep in control of those (not in the bi-weekly meetings)?
c) I miss the synchronisation of the master/development branche to a fork... 
d) I think one way of working should be adopted, all devs using forks.
e) this kind of discussions should be done in Slack.

**Comment by edwinvandenbelt** [comment]
f) is there need for several branches when you can cherry-pick commits to merge?

**Comment by Threore** [comment]
> Isn't it enough to have a master branch and a development branch? 
I've thought about this. If we only have one development branch, any bug fixes and features that contain breaking changes have to **live indefinitely** in their own branch until we decide that our one `develop` branch is no longer for the next minor version but for the next major version.

 If that takes a while, this leads to a nightmare when trying to merge all those features and bug fixes that have accumulated over time. What you want is that if feature A for v2.0 has been created and someone wants to start work on feature B for v2.0, that they start from the branch containing feature A. If completed features aren't merged into a develop branch, this is very hard to do right as it becomes hard to tell what the most recent branch is that isn't still being worked on.

There is indeed a price to pay in that very often changes to `develop-minor` should be incorporated in `develop-major` also, but I think that it is worth it.

**Comment by edwinvandenbelt** [comment]
And how about a master and a development branche, where the development branche can be branched for features. During the meetings we can have a look at each branche and decide if it's merged to the development branche. If it's urgent enough, this could mean that the development branche must be released as major. If the feature is not urgent, the merge can be postponed until a later, major version.

**Comment by ro5k0** [comment]
TBD after next meeting on 01/04
