### ISSUE TITLE
Response statuscodes on errors

### ISSUE THREAD

**Issue by dejelger** [TOMP-WG/TOMP-API#118]
Each of the TOMP endpoints have a 'happy flow' statuscode (200-range), and a 'less happy-flow' with statuscodes 400, 401, 403, 404, 409 of 410. 
However, in some cases problems/issue/unforseen situations can occur within the MSP or TO systems. These kind of situations usually result in a 500 (-range) error code, but in the TOMP spec this is not possible. 
For example: A user tries to create a booking, but during the request there's a production hickup ('extreme situation'). What kind of result statuscode should the user receive? None of the available 400/401/404/409 statuscodes applies.

**Comment by edwinvandenbelt** [comment]
Should we add those to each endpoint? Is there an added value? Or should an comment somewhere to clarify this?

**Comment by dejelger** [comment]
Yes I think it should be added to each endpoint. The added value is that the http 400-range is meant for "client error responses", in other words: the request is wrong, and the user did it. 

But, when there is something wrong with the operator. e.g. the internal systems of the operator fails for some reason (e.g. database is down), there should be a place for that. 

The format of the response could be the same as other error-responses:
```
{
  "message": "internal error",
  "code": 12345
}
```
