### ISSUE TITLE
renaming "provide-ids" in /planning-options

### ISSUE THREAD

**Issue by stephanroosli** [TOMP-WG/TOMP-API#144]
**Problem**
The name of the attribute `provide-ids` in `planning-options` is not meaningful enough to describe what it actually does. It makes it obvious when you need to explain to the workings of the API to somebody. 
It almost has a touch of being a "technical" attribute, where in fact it is a (very important) "business" attribute, which may change the behaviour within a TO significantly. Setting this attribute to `true` means, that the TO has to "reserve" this request (persist an initial offer) so that it can subsequently be booked. This still means, that the response will include "ids" that can then be used in the following calls (i.e. to `/booking`).
_Maybe we should even think about renaming the terms `id` as well, as they seem too generic. Will open a separate issue for that later..._

**Resolution**
Use a self-explanatory term instead. 

**Proposal**
use the following term:
- `reserve` = [true|false]

**Disclaimer**
of course, if anyone has a better suggestion, just drop it here!

**Comment by edwinvandenbelt** [comment]
discussion in github

**Comment by edwinvandenbelt** [comment]
WT1: it's actually not a reservation, it's just a request to generate ids to refer to.

**Comment by stephanroosli** [comment]
ok, it's not a "resservation" per se. Agree. But it does mean, that the offer is "binding", and can subsequently be reserved.

We sometimes use the term "pre-reservation" in our system (e.g. B2P). Maybe that's better ? `pre-reserve`

I just would like to see it more "speaking for itself". Because nobody wants "ids"... what is needed is the ability to book what's received in the response, so maybe `make-bookable` or `make-offerable.` Sounds odd but this comes closer I think... or `save/retain-for-offering` or `make-sure-I-can-book-it`...

**Comment by edwinvandenbelt** [comment]
Ok. clear.
