### ISSUE TITLE
Belgium / Vlaanderen

### ISSUE THREAD

**Issue by skinkie** [TOMP-WG/TOMP-API#151]
The current standard in Belgium;

Mobiliteit: Trips & Aanbod (Applicatieprofiel)
https://data.vlaanderen.be/doc/applicatieprofiel/mobiliteit-trips-en-aanbod

**Comment by Tjalle** [comment]
Ah, they've taken it out of test. Thnx for sharing.

**Comment by pimmeh** [comment]
Thanks for the information. This is not a bug or feature request so I'm going to close this issue. Further discussion can be done in slack.
