### ISSUE TITLE
[FEATURE REQUEST] Specify errors

### ISSUE THREAD

**Issue by edwinvandenbelt** [TOMP-WG/TOMP-API#163]
## Is your feature request related to a problem? Please describe.
When errors occur in endpoints, there is now a generic error object. This is not convenient for the MP or TO, errors might be reported in several ways.

## Urgency
Major, because it would increase the ease of implementation

## Additional context
It is in all the endpoints

## Describe the solution you'd like
Describe on the wiki how the error object should be filled (format for missing fields, invalid combinations, etc)

## Describe alternatives you've considered
To leave it, would cost MPs and TOs considerably more money to cope with all the different errors.

## Possible Implementation
Go through all the endpoints and document the possible error(type)s and how to report them

**Comment by pimmeh** [comment]
I started working on this page, it's not yet finished and not yet ready for review: https://github.com/TOMP-WG/TOMP-API/wiki/Error-handling-in-TOMP
