### ISSUE TITLE
[BUG]: mandatory fields

### ISSUE THREAD

**Issue by edwinvandenbelt** [TOMP-WG/TOMP-API#165]
## API Version
0.5.0

## Summary
The API is not strict enough, mandatory fields are not marked as required

## Expected Behavior
Every field should be marked as required if it is mandatory

## Current Behavior
It's very merely used in the current version

## Possible Solution
Go through the API and mark all mandatory fields

## Possible Implementation
Go through the API and mark all mandatory fields

**Comment by pimmeh** [comment]
Note: we only need to specify the really really mandatory fields. Not the ones that we think are handy or something.

**Comment by ARBaart** [comment]
PR #175 for issue #174 removes a few required fields that aren't in the object. @kushshr Take a look at those so we actually replace them with the correct required fields instead of just removing them.
