### ISSUE TITLE
[FEATURE REQUEST] 0.5 release?

### ISSUE THREAD

**Issue by brylie** [TOMP-WG/TOMP-API#173]
Is there a release process for TOMP API versions? What is the timeline for making the 0.5.x releases?

**Comment by ARBaart** [comment]
0.5.x releases are for hotfixes only (which #175 is) and should not contain any real changes, just fixes to something we broke by mistake. To quickly release them we tend to just await a number of positive replies in WT1.

Larger releases are prepared in a develop branch, move to a release branch for final changes and are merged into master as a new 0.x.0 release after approval by the biweekly meeting.

**Comment by brylie** [comment]
@ARBaart there just doesn't seem to be any release from the 0.5 series:

![image](https://user-images.githubusercontent.com/17307/83266010-f4c15c80-a1ca-11ea-8a9d-70f10b3c0f7f.png)

**Comment by pimmeh** [comment]
This is not an issue. Please use slack (invite link in the READ.ME) for these kinds of questions or send an email.
