### ISSUE TITLE
[FEATURE REQUEST] Self describing facilities

### ISSUE THREAD

**Issue by edwinvandenbelt** [TOMP-WG/TOMP-API#180]
## Urgency
Might be necessary for (inter)national scale up

## Additional context
To facilitate interoperability, the API should be the same over all the TOs and MPs. This isn't possible. Therefore we have to know which version of the API a certain TO/MP has implemented and what endpoints.

## Describe the solution you'd like
A version-independent endpoint describing the implemented endpoints per version and other information to make it easy to setup a new connection.

## Describe alternatives you've considered
Registrating this information at a NAP. I'd like to think that the NAP will request this endpoint to get his data.

**Comment by brylie** [comment]
FWIW, FLoU Analytics designed a ["service discovery" API](https://github.com/maas-alliance/apis/blob/master/specifications/service-registry.yaml) as commissioned by the city of Helsinki for the [BoMaaS research initiative](http://www.tut.fi/verne/aineisto/B2_Haapamaki.pdf).
