### ISSUE TITLE
[BUG] Duplicate functionality in planning options timestamps

### ISSUE THREAD

**Issue by ARBaart** [TOMP-WG/TOMP-API#184]
## API Version
0.5.3

## Summary
When POSTing to `/planning-options/`, one receives an `Expires` header in the reply with the timestamp when the options are no longer valid, and the `planningOptions` object has a field `validUntil` which does exactly the same.

## Expected Behavior
Functionality should not be duplicated

## Possible Solution
Remove `validUntil` and leave this meta information in the header that is commonly used for it

**Comment by edwinvandenbelt** [comment]
I would say, remove the Expires in the header. The result will be stored, the header fields probably not.

**Comment by ARBaart** [comment]
Ah, I arrived at the opposite conclusion because the Expires header is a standard HTTP thing therefore could be built-in in frameworks people use. I'll switch it around then :)
