### ISSUE TITLE
[FEATURE REQUEST] Being able to request a payment/journal-entry on a booking basis

### ISSUE THREAD

**Issue by pimmeh** [TOMP-WG/TOMP-API#209]
## Is your feature request related to a problem? Please describe.
At the moment, it is possible to request a journal entry through the GET/payment/journal-entry. This is on a timerange basis. That is very handy, if you want to request a lot of bookings at once. However, as soon as a single booking is finished, we as a MaaS Provider, want to request the total costs of that specific booking with a specific bookings id. For instance, when a shared car has been used and the total costs depends on the distance driven, the end user needs and wants to know what the costs were. It is quite cumbersome to request an entire list, if you only want just the one.

## Urgency
Major (the TOMP API works as advertised but this is really neccessary to implement). For now, with not much volume and traffic, it's doable with the current implementation. However, when there are more and more bookings, load on the transport operator systems will rise when all the MaaS Providers will request entire lists of journal entries that are not neccessary.

## Describe the solution you'd like
We would like an endpoint similar to GET/payment/journal-entry but then for one specific booking id that would return the journal entry for that booking.

## Describe alternatives you've considered
None.

## Possible Implementation
See the solution description.

**Comment by eborremans** [comment]
@pimmeh I am following this request with interest as I incidentally had a conversation today about trip cost with one of our TOMP consumers. Just to make sure I understand your request. When you say 'end user' I suspect you mean the person using the asset? A journal entry is about the amount due from MSP to TO right? I would expect as an MSP you need the journal to be able to do your own calculations and then inform the end user. Is that right?

**Comment by pimmeh** [comment]
Yes you understand me correctly. Either you bill the amount 1 on 1 to the end user or you add your own margin to it or not. Either way, the MSP needs to know the amount the TO bills to the MSP, so that the MSP can then do what he wants with that information.

**Comment by eborremans** [comment]
Thanks! I wanted to ensure I properly understood the intent of this API
