### ISSUE TITLE
[BUG] or [CHANGE REQUEST] Version number 0.6.0 in 0.9.0

### ISSUE THREAD

**Issue by eborremans** [TOMP-WG/TOMP-API#210]
## API Version
0.9.0/0.6.0 (API says 0.9.0 but POST /legs/{id}/events says 0.6.0)

## Summary
Why do we use both timestamps and Strings to denote dates? In particular the isReservedFrom and isReservedTo fields in the /legs/{id}/events request are modelled as strings rather than timestamps. Possibly more endpoints contain this issue.

## Expected Behavior
I suggest to use timestamps everywhere for consistency.

## Current Behavior
String instead of timestamp is being used

## Context (Environment)
Consistency is required for obvious reasons.

**Comment by ARBaart** [comment]
We decided to use (standardised) strings for datetime instead of timestamps. 

Is there somewhere where we left time as a number?

**Comment by edwinvandenbelt** [comment]
Yes. line 2783

**Comment by eborremans** [comment]
This issue was originally about the inconsistency of some date types. While describing the version in which I found it I also saw an inconsistency in the version numbering. I guess that requires a separate ticket rather than changing the title of this one. I am a bit confused now.

**Comment by edwinvandenbelt** [comment]
Sorry! We didn't look close enough to this issue. In version 0.6.0 (internal version) we switched from epoch timestamps to human readable timestamps. I have looked again over the complete API, and I cannot find any timestamp (epoch) left. Do you have found any endpoint with numeric timestamps?

**Comment by eborremans** [comment]
Ok, no problem. I believe you if you say you changed it everywhere :-) Even though the example values suggest it, you may want to specify in the swagger spec that we are talking about a datetime format according to ISO 8601 as done for the country codes.
