### ISSUE TITLE
[BUG] or [CHANGE REQUEST] /payment/{id}/claim-extra-costs is a patch?

### ISSUE THREAD

**Issue by edwinvandenbelt** [TOMP-WG/TOMP-API#219]
## API Version
0.9.0

## Summary
The endpoint /payment/{id}/claim-extra-costs is a PATCH. Is this correct?

## Expected Behavior
It's not a patch on existing objects. Technically speaking I think it should be a POST

## Possible Implementation
Change PATCH to POST

**Comment by eborremans** [comment]
I guess it depends on how you implement it. the use of an id suggests that you can update an existing regular payment (with that id) with extra cost. however in such a case i would expect that the payment model has a separate field for extra-cost (you don't want to just increase the amount on the original payment without knowing what it was for). in the request i do not see such an extra field. and i think it shouldn't. normally in billing systems, extra cost will be handled in a separate payment. so yes, this endpoint should NOT be a PATCH, rather a POST for an additional payment for the extra cost.
