### ISSUE TITLE
[FEATURE REQUEST] The availability at a particular station/hub. 

### ISSUE THREAD

**Issue by kushshr** [TOMP-WG/TOMP-API#221]
## Is your feature request related to a problem? Please describe.
Some TOs dont want to share the available-assets endpoint. So, for a station/hub, its not possible to get the real time availability of an asset. 

## Urgency
Major - Hub based availability is not taken care of.  

## Describe the solution you'd like
Adding an availability number (number_assets) in the GET /operator/stations/ endpoint. 

## Describe alternatives you've considered
GET /operator/available-assets, but some TOs dont want to expose this info.

**Comment by edwinvandenbelt** [comment]
what's the reason they don't want to expose available-assets? They are able to return results only to 'trusted' partners.

Implementing this implies that the endpoint of stations goes from static to dynamic. Therefore we'll end up with 2 dynamic endpoints for those who want to implement the available assets.
