### ISSUE TITLE
[FEATURE REQUEST] Add more response to `POST /legs/{id}/events` endpoint

### ISSUE THREAD

**Issue by canvural** [TOMP-WG/TOMP-API#222]
## Is your feature request related to a problem? Please describe.
`/POST legs/{id}/events` endpoint is used to actually start the leg. And this means in some cases TO will make some effort to open the car for example. (Using some telematic provider etc.) If something goes wrong in this process, TO should respond back to MP, and let the MP try again after some time or immediately. 

But right now there is no response in the spec to allow this situation. Can't use `400` because request is actually correct.
## Urgency
Minor

## Describe the solution you'd like
Adding a new status code in 5xx range would be ok. Maybe `503` with `Retry-After` header.

**Comment by eborremans** [comment]
@canvural since we are also currently implementing trip execution scenarios I am following tickets like these. Just out of curiosity, when you are saying '/legs/{id}/events endpoint is used to actually start the leg' do you mean this is called by MSP or TO? In any case, in the enums described in the POST variant there indeed does not seem to be an option that can be used (by the TO) if something went wrong during the start of a leg. It may indeed be a good addition to provide for this.

**Comment by canvural** [comment]
@eborremans  Yes, I mean MP calling TO to start the leg.

But this has nothing to do with enums. I'm suggesting there should be a new response with status code in the range of 5xx. To indicate something went wrong while trying to start the leg, and MP should try again later.

**Comment by edwinvandenbelt** [comment]
@canvural Do you call this endpoint and wait until the lock opens? Doesn't it take too much time, thereby blocking the endpoint for other users? Or are you helped by using an asynchronious approach: return 200, but when the lock is jammed, use the support endpoints to report this.

**Comment by canvural** [comment]
@edwinvandenbelt  I'm implementing the TO side. And yeah implemented it in a synchronous way right now. The request doesn't finish until we have a response from the telematic that the vehicle uses.

I didn't find a good way to do it asynchronously in the spec. Best way would be, after MP calls `POST legs/{id}/events` endpoint in TO, TO returns 202 accepted, then TO calls a webhook in MP side to report the status of the event. If it was successful or did it fail etc. But as far as I can see there is no workflow like that. (At least in 0.5.3. We are stuck using that version because of MP wants that way)

**Comment by canvural** [comment]
> Doesn't it take too much time, thereby blocking the endpoint for other users?

And usually, our calls to telematic provider takes a maximum of 15 seconds. So, not that bad I'd say. 

I don't understand why would it be blocked for other users. We can accept multiple requests at the same time. (For different leg ids)
