### ISSUE TITLE
CHANGE REQUEST: "properties" in Asset is keyword

### ISSUE THREAD

**Issue by eborremans** [TOMP-WG/TOMP-API#231]
## API Version

0.9.9
## Summary

The 'properties' field in the Asset object causes trouble with some tools. Our swagger implementation cannot handle the use 
of a 'keyword' as the name of a field. This is probably a bug in the tool, but not within our hands to have fixed on the short term. 
## Expected Behavior

Rename it to assetProperties or something similar

## Possible Solution

Rename it to assetProperties or something similar

## Steps to Reproduce

1. Will be provided after some more investigation is done.
2.
3.
4.

**Comment by eborremans** [comment]
![image](https://user-images.githubusercontent.com/9337704/91986697-4f6bd680-ed2d-11ea-9cbb-4553dbe6d9af.png)

**Comment by eborremans** [comment]
thanks edwin for the quick resolution

**Comment by edwinvandenbelt** [comment]
you're welcome! We agreed on merging everything next week Wednesday.
