### ISSUE TITLE
[CHANGE REQUEST] add deeplinks (rental-uris) from GBFS2.0 in TOMP/operator-information

### ISSUE THREAD

**Issue by stephanroosli** [TOMP-WG/TOMP-API#237]
## API Version
0.9/1.0 (latest)

## Summary
Add the deeplinks `"rental_uris"` to the TOMP operator-information

## Expected Behavior
Operators can implement TOMP operator-information and provide the same information that they publish through an GBFS2.0 endpoint. 

## Current Behavior
The fields were added in GBFS2.0 and are not present in operator-information.

## Possible Solution
Add the fields as optional to the operator-information spec

## Steps to Reproduce
n/a

## Context (Environment)
This will allow companies who already have GBFS2.0 implementation to "switch" completely to TOMP without loosing any information.
In Switzerland there is an initiative to collect all sharing partners through their respective GBFS-endpoints into one "combined" GBFS feed on an open data platform - including the deeplinks. It is known, that this is "only a first step" in the digitalization of the mobility market, but it creates initial awareness in the industry. If sharing providers implement TOMP, then they wouldn't need to also implement the GBFS Endpoint.

## Detailed Description
see above

## Possible Implementation
see above

**Comment by edwinvandenbelt** [comment]
hmm. GBFS 2.0 adds rental_uris on 3 levels. 

In the **system_information** we could add the URLs for the stores and the discovery_uri ,to find out if an app is on your system. Of course the TO app can be published this way, but has only limited value (unless a deeplink requires the app).

In the station_information you could add these urls as well to jump directly to the appropriate station. It doesn't serve the goal of the TOMP...

Adding it in the available_assets will imply also adding it into the planning (it will be in the 'asset' object). How far do we need to go to be GBFS compliant? This is in direct conflict with the principals of TOMP API.

In my opinion we should add the apps (store & discovery) in the /operator/information, but not in the other 2 endpoints.
