### ISSUE TITLE
[CHANGE REQUEST] Add useAssetType (conform useAsset) in planning

### ISSUE THREAD

**Issue by eborremans** [TOMP-WG/TOMP-API#238]
## API Version
0.5.0, 0.9.0

## Summary
Currently it is not possible to select the asset type in the plannings(-options) endpoint. For TOs that do not support booking of specific asset instances this may be a problem if they support more than one asset type.

## Expected Behavior
A way to select the asset type (as reported in the operator information endpoint) should be made available to the planning scenario.

## Current Behavior
Only assetIds can be specified

## Possible Solution
Add a field to the plannings request where the asset type id(s) (assetType#id) can be specified.

## Context (Environment)
As our TO does not support the booking of specific assets, we'd like the customer to be able to select an asset type so we can return the proper plannings options.
As a side note: note that in the future we'd like to specify this (lack of ) capability with process identifiers. However, it is not clear to us how to do this. 

## Detailed Description
add String [] field useAssetTypes (analogous to useAssets) for holding the assetType#id's

**Comment by edwinvandenbelt** [comment]
Hmm. Eddy, Is the process this way: the MP shows all available assetTypes from the TO in the app, the end user selects one assetType to book?

**Comment by eborremans** [comment]
yes, that is how it works
