### ISSUE TITLE
[FEATURE REQUEST] Specify user groups

### ISSUE THREAD

**Issue by edwinvandenbelt** [TOMP-WG/TOMP-API#247]
## Is your feature request related to a problem? Please describe.
Sometimes a TO can supply assets to specific user groups. It's a concept not yet provided in the API

## Urgency
Major (the TOMP API works as advertised but this is really neccessary to implement), because we have to 'abuse' the 'cards' field in the plannings call for this. 

## Additional context
In a B2B context employees can have access to extra assets. These assets cannot be used by everyone. This is based on a peer-2-peer contract, so the user groups are not published to the public.

## Describe the solution you'd like
Add an extra field to the planning: 'userGroups': string-array

**Comment by jensfrandsen** [comment]
Here are my thoughts on adding the request filter:
 - The feature request makes sense for when wanting to give exclusive access to hidden assets. The use cases as I see it:
  - f.x. car sharing / renting where cars are reserved for a limited crowd, f.x. residents of a building signed up to a carsharing service (although normally these services are A to A services, so it could be discussed if this is a good use case)
  - Donkey Republic bike share f.x. has this concept built in where a limited group of users can get access to "hidden" pickup points. A typical use case is in a industrial campus where companies pay to get access to their employees. 
 - a string array seems like best option to input the groups

Challenges
 - In DR service the access to exclusive assets are not tied to a usergroup like value inputted in the request as it opens for people to read that usergroup value and misuse it. Instead we provide the exclusive assets based on the user being authenticated. In TOMP the use case is obviously different as it is not an API exposed to an app. But what I would like to get your input on is whether you can see a security issue in this. I guess in reality the TO would have a specific agreement with the MP that when this is inputted these specific assets are exposed, but I would still like your input on if you see any security issues in this as it seems that the security around this is solely handed on the MP side.

**Comment by jensfrandsen** [comment]
A second question that came to my mind is: Does this input add assets to the "normal" result set or does it limit the result only to the assets that are exclusive to this user group. I would like your input on whether this should be spec'ed or left up to TO?

**Comment by edwinvandenbelt** [comment]
I'd say that we add these assets to the normal set, thereby facilitating one request for planning. Otherwise the MP should make 2 planning calls for people in user groups and merge them. The costs are in every planning option, so that's not a problem.
