### ISSUE TITLE
[CHANGE REQUEST] Post plannings endpoint does not return an Id

### ISSUE THREAD

**Issue by MartijnvAdrichem** [TOMP-WG/TOMP-API#254]
## API Version
1.0.0

## Summary
At the moment the "POST /plannings" endpoint returns a list of bookingoptions, but does not return an ID of the entire object itself. This makes it impossible to use the endpoint "GET /plannings/{id}" because there is no ID available.

## Expected Behavior
An ID should be returned for every planningobject so it can be used again in a later moment.

## Current Behavior
No ID is returned making it impossible to use the "GET /plannings/{id}" endpoint

## Possible Solution
```json
{
  "id": xxx, // add this field
  "validUntil": "2020-10-07T08:08:48.964Z",
  "options": []
}
```

## Context (Environment)
The issue doesn't really affect me right now, but it makes the endpoint "GET /plannings/{id}" confusing to implement (if not useless).

**Comment by edwinvandenbelt** [comment]
Martijn, I guess you're right. The GET /plannings/{id} shouldn't be anymore in the API. I thought we'd removed all the optional planning endpoints. My solution should be 'remove this endpoint'. I haven't adviced anyone to implement it; it is quite a suprise to me it's still in there. And I don't know anyone who has implemented it.

**Comment by MartijnvAdrichem** [comment]
Hi Edwin, 

I will ignore the endpoint for now then, thanks!
