### ISSUE TITLE
[BUG] Code generation for ASP.NET Core Models

### ISSUE THREAD

**Issue by BramManuel** [TOMP-WG/TOMP-API#258]
## API Version
1.0.0

## Summary
When downloading a Server Stub from [Swaggerhub](https://app.swaggerhub.com/apis/TOMP-API-WG/transport-operator_maas_provider_api/1.0.0), the models that contain a Country Property, for example "Address". They expect a Country Model. In the TOMP specification there it is stated that a Country is a "string" with a min and max length of two ([Swagger TOMP-API](https://app.swaggerhub.com/apis-docs/TOMP-API-WG/transport-operator_maas_provider_api/1.0.0#/address)). This is not consistent with each other.

The same applies for the following Schemas:

- Duration (interger)
- Distance (integer)

## Expected Behavior
When generating a Server Stub the country model should be generated as a "string".

## Current Behavior
The Server Stub Models contain a Country Model as reference.

## Steps to Reproduce

1. Got too (https://app.swaggerhub.com/apis/TOMP-API-WG/transport-operator_maas_provider_api/1.0.0).
2. Select Server Stub > aspnetcore
3. Move to aspnetcore-server-generated > src > IO.Swagger > Models > Address

**Comment by edwinvandenbelt** [comment]
Hello Bram,

the generator replaces probably 'simple' classes, directly derived from flat types by it's flat types, without taking notice of other limitations (min, max, length etc). This is not a concern for the API, but is something in the generator. The generators are maintained in https://github.com/swagger-api/swagger-codegen. The java generator does the same. But why is this a problem? Isn't the generated code usable?

**Comment by BramManuel** [comment]
Hello Edwin,

Thanks, I did not know that, I will take a look there.
And close this issue.

It's not usable without a lot of adjusting.
