### ISSUE TITLE
[FEATURE REQUEST] Handle multi-region TOs

### ISSUE THREAD

**Issue by jensfrandsen** [TOMP-WG/TOMP-API#265]
## Is your feature request related to a problem? Please describe.
We have a lot of stations around Europe in many different cities. It seems to us that the API does not consider different regions so widely.  There’s the regions endpoint in Operators, but the regions are not used anywhere else it seems.
So firstly, calling stations or available-assets endpoints in operator would return a very long list. That is problematic for us (performance wise) and probably also for the MP.
Secondly planning and booking doesn’t have a region notion. From an MP perspective I would assume that having a city perspective is needed. An MP searching for a trip in f.x. Paris wouldn’t call planning on a TO operating in Madrid only. Also assets (in our system and most likely others as well) can not be returned in another city. So searches should take place inside one city for our city.
One example where this issue is very visible is the pricing. There’s no region coupling on pricing, and pricing in different cities around the world have different pricing levels, currencies and vat rates.
Lastly, if planning and booking were limited by a city/region id it would probably make TO’s implementation run much faster.
We suggest that this city concept is more apparent in the API.

## Urgency
For us this is a blocker for starting implementation as it dictates how the basics of implementation is done. 

## Additional context
We don’t mind both ways suggested below, but the namespace one seems more clean. In the alternative solution we would make a region input mandatory in our implementation and that might not be easy to catch as this would be one of many inputs, where the namespace is much more easy to understand.

## Describe the solution you'd like
Implement a city/region namespace on the TO side. f.x. xxxxx.com/tomp/copenhagen/operator/?. This is how GBFS solved it. This would require knowledge from the MP about what TO’s are present in which cities (our experience is that MP’s are mostly interested in certain cities and not just all of them). It would require little or no changes to the API. All info would simply be scoped by the namespace. Perhaps a city name and country code in operators would be helpful… Train operators and other operators that operate across all regions at once could simply just have everything in one namespace.

## Describe alternatives you've considered
Implement the cities using the regions endpoint in Operator. This would then require that the regions endpoint id’s would be used as inputs for pretty much all other endpoints, f.x. pricing but most likely we would also like this to be inputted to planning and booking.

## Possible Implementation
If the the suggested solution is picked then the change might be as simple as a Wiki update. If the alternative solution is selected then most endpoints needs to have a region_id input and the operator/regions endpoint might need a little brush-up

**Comment by edwinvandenbelt** [comment]
please have a look at #244 . Does this cover most of it? And the city name is of course not necessary, because planning requires lon/lat.... The city or region is derivable. And paging is also available from 1.1.

**Comment by jensfrandsen** [comment]
Yes this is the same issue, his proposal is my alternative one. Not the best. But I can discuss it there instead

**Comment by stephanroosli** [comment]
I'd like to throw in another aspect.

MaaS-platforms are generally active in a bordered geographical area and have **commercial agreements** with the provider only for this area (generally an urban area around a town/city). If the same provider is also active in a another city (even in the same country) the MaaS-operator may not (for commercial/contractual reasons) be able to book these.

This is also a "regionality" aspect that needs to be considered. 

At least that is the current situation, but of course the vision is that MaaS-Apps will be able to "roam" in other areas as well. But in this case we need to tackle some kind of "digital contract".

**Comment by jensfrandsen** [comment]
I agree Stephan. For this reason it also makes sense for me to handle regions with name spacing. That makes the division very clear, while it doesn't prevent some TO's in merging multiple regions if they logically belongs together.

**Comment by piotrj** [comment]
Information about how to handle multiple regions are in Wiki here https://github.com/TOMP-WG/TOMP-API/wiki/Multi-region-TO-implementation.
