### ISSUE TITLE
[BUG] Inconsistent vatRate / taxRate in pricing plans

### ISSUE THREAD

**Issue by MartijnvAdrichem** [TOMP-WG/TOMP-API#271]
## API Version
1.0.0

## Summary
in the Pricing plans -> fare -> parts -> a property "vatRate" exists, but in the example  its called "taxRate"
the example:
```json      "parts": [
        {
          "amount": 9.96,
          "currencyCode": "EUR",
          "taxRate": 21,
          "type": "FLEX",
          "unitType": "HOUR",
          "units": 1
        }
```
the schema:
```json

vatRate

```
## Possible Solution
Which one is correct?

**Comment by canvural** [comment]
I believe `vatRate` is correct. You should always trust the schema. The example needs to be updated.

**Comment by edwinvandenbelt** [comment]
correct. There are sometimes discrepancies in the examples or comments. Sorry about that. The schema is always leading.
