### ISSUE TITLE
[BUG] missing fields in 'asset' and 'assetType' schema definitions of TOMP-API.yaml

### ISSUE THREAD

**Issue by mtoorop-ximedes** [TOMP-WG/TOMP-API#272]
## API Version
1.0.0

## Summary
The `TOMP-API.yaml` contains two schema definitions that appear to have an incorrect definition in them.

### assetType schema definition
`properties`  is set as required in the YAML definition but it is not listed in the list below as a field. So either it should not be in a required field or the field should be included.

The line in question: https://github.com/TOMP-WG/TOMP-API/blob/353d803e0e157ff9d55480d5796a596d70c3f95c/TOMP-API.yaml#L1221

### assetType schema definition
`amountAvailable` is set as required in the YAML definition but does not exist, I think this is a typo of the `nrAvailable` field that is defined below that.

The line in question: https://github.com/TOMP-WG/TOMP-API/blob/353d803e0e157ff9d55480d5796a596d70c3f95c/TOMP-API.yaml#L1277

**Comment by edwinvandenbelt** [comment]
Hello Marcel, indeed. Both bugs are result of recent changes. 'properties' is renamed to 'sharedProperties' (0.9.0 to 1.0.0) and 'amountAvailable' is renamed to 'nrAvailable' (0.9.0 to 1.0.0).

**Comment by edwinvandenbelt** [comment]
Comment of Bruna (#281): 
The assetType object contains a property named "amountAvailable" on the required items and it doesn't really exist as a property on that object. But lead us to question wether the nrAvailable property is related to this one and if you meant that it should be mandatory.
That appears to be a mistake during the refactoring between versions 0.5 and 1.0.0.
As we are looking into this from the perspective of a PTO (trains and busses), field nrAvailable is not really relevant.

__Expected Behavior/Solution__
Property amountAvailable should not be present on the required list as it's not a valid property anymore
Can you confirm to us that the nrAvailable will not be mandatory
