### ISSUE TITLE
[BUG] nrAvailable / amountAvailable on AssetType 

### ISSUE THREAD

**Issue by brunaguize** [TOMP-WG/TOMP-API#281]
## API Version
1.0.0

## Summary
The assetType object contains a property named "amountAvailable" on the required items and it doesn't really exist as a property on that object. But lead us to question wether the nrAvailable property is related to this one and if you meant that it should be mandatory. 
That appears to be a mistake during the refactoring between versions 0.5 and 1.0.0.
As we are looking into this from the perspective of a PTO (trains and busses), field `nrAvailable` is not really relevant.

## Expected Behavior/Solution
1. Property amountAvailable should not be present on the required list as it's not a valid property anymore
2. Can you confirm to us that the nrAvailable will not be mandatory

**Comment by edwinvandenbelt** [comment]
Hello Bruna, you're correct. It was already noticed in issue #272. And indeed, the nrAvailable should not be mandatory. I'll write this also down in issue 272.
