### ISSUE TITLE
[FEATURE REQUEST] Additional fields needed to manage shared vehicule stations and trip planning calculation

### ISSUE THREAD

**Issue by fhenryot** [TOMP-WG/TOMP-API#287]
## Is your feature request related to a problem? Please describe.
Trip planning calculation required 2 conditions to propose a trip via shared vehicle from hub to hub.
1/ availability  of one vehiule at starting hub at departure time
2/ At least one (or more) available place(s) at arrival hub at expected time of drop off.

The current version of TOMP doesn't provide the number of available parks.
Only number of vehicle is provided via asset-availabilities, (in v1.0)

## Urgency
  To limit the number of different requests, it makes sense to group  these additional information at station level (versus asset today)

## Describe the solution you'd like
 Enrich the response of   /operator/stations  endpoint with addtional fields
+ "nrAvailable"   Integer  (relocate from asset method)
+ "nrEmpty"      Integer    (new)
+ "totalCapacity"  Integer  (new)

Note : "nrEmpty"  must exclude park under maintenance , then  "nrAvailable"+ "nrEmpty" <= "totalCapacity"

## Describe alternatives you've considered
  No alternative

## Possible Implementation

response sample;
[
  {
    "stationId": "XX:Y:12345678",
    "name": "Island Central",
    **"nrAvailable" : 6,
    "nrEmpty" : 4,
    "totalCapacity" :10,**
    "coordinates": {
      "lng": 6.169639,
      "lat": 52.253279
    },
    "physicalAddress": {
      "streetAddress": "example street 18, 2nd floor, 18-B33",
      "areaReference": "Smallcity, Pinetree county",
      "postalCode": "string",
      "country": "NL"
    },
    "crossStreet": "on the corner with Secondary Road",
    "regionId": "string",
    "rentalMethods": [
      "CREDITCARD",
      "PAYPASS",
      "APPLEPAY"
    ],
    "rentalUrl": "https://www.rentmyfreebike.com"
  }
]

**Comment by piotrj** [comment]
@fhenryot This topic of available parking spots at a station has been touched before and we ended up with an idea where parking spots will be part of available assets as described here: https://github.com/TOMP-WG/TOMP-API/wiki/Available-assets#providing-number-of-available-bike-docking-places-or-other-parking-spaces. 

We were considering a solution similar to `nrEmpty` but then few problems were raised where parking spots may differ between each other (for example parking spot with charger for e-bike and without a charger). Therefore, we went with this generic approach. You can read more of this discussion here: https://github.com/TOMP-WG/TOMP-API/issues/289

**Comment by piotrj** [comment]
@fhenryot just wanted to make sure whether what I said makes sense for you and whether this ticket can be closed.

**Comment by fhenryot** [comment]
@Piotr   Thx, I confirm this covers the need.  Ticket can be closed.
Thanks a lot!
When the release date and which TOMP version should take it into account ?
 Fab

Le jeu. 4 févr. 2021 à 22:30, Piotr Jakubowski <notifications@github.com> a
écrit :

**Comment by piotrj** [comment]
@fhenryot actually that `PARKING` assetClass is in the current version of TOMP. So you can have that set up already and it will be compliant with current version of the specification.

**Comment by fhenryot** [comment]
Great, thanks!
