### ISSUE TITLE
Battery percentage in assets

### ISSUE THREAD

**Issue by kushshr** [TOMP-WG/TOMP-API#288]
As an MP, if I get assets in a POST /plannings I made towards the TO, I want to pick up the asset based on the percentage of the battery in their electric bikes/cars. During the trip execution too, it makes sense to have an endpoint which provides dynamic information about the asset. For example, as an MP, I want to show during the trip execution the battery remaining so that the user can make an informed decision about how they proceed with their trip. 

Urgency: Critical
We need to do this and we dont want to implement anything that goes beyond TOMP. 

Of course the additional properties object of the asset can be used. But, as battery percentage is a "generic" property for a lot of TOs, I think there should a specific field "battery_percentage" in the asset object. 

For battery during trip exuection, we can use the legs/id/progress endpoints hopefully.

**Comment by piotrj** [comment]
@kushshr seems that assetProperties already has `stateOfCharge` ... isn't this what you are looking for?

**Comment by edwinvandenbelt** [comment]
@kushshr I think Piotr has right. The stateOfCharge property has this functionality. It can be found in the result of the planning 
(planning.options.legs.asset.overridenProperties.stateOfCharge). It can also be retrieved using /legs/{id}. It returns also a leg.

**Comment by kushshr** [comment]
@piotrj @edwinvandenbelt Didnt kn ow about this field.  Closing this issue. Thanks!
