### ISSUE TITLE
Opening hours should be station wise

### ISSUE THREAD

**Issue by kushshr** [TOMP-WG/TOMP-API#302]
The opening and closing hours can be station wise and they should be available with GET /operator/stations rather than GET /operator/operating-hours. The current stucrure in GET /operator/operating-hours also does not allow to put one object for one station as it assumes that stations are open for the same start time and end time for all days of the week while in reality these hours may vary per day of the week. 

Also, it seems from the endpoint's name that it provides information about the operating hours of the opeator rather than per station. 

Super urgent. 

Alternatives: 
It could be still used with GET /operator/operating-hours, but then the structure wont be so nice.

**Comment by piotrj** [comment]
@kushshr so I looked again at the api as it is right now and it seems that what you are trying to solve is possible. You also mention in the issue that it is possible but I just wanted to make sure that we are on the same page.

So when a station `"123"` is open at different hours on weekdays and other hours on Saturday and closed on Sunday then it seems that it can be represented as so:

```
[
  {
    "userType": "MEMBER",
    "stationId": "123",
    "startTime": "9:30",
    "endTime": "22:30",
    "days": [
      "MON", "TUE", "WED", "THU", "FRI"
    ]
  },
  {
    "userType": "MEMBER",
    "stationId": "123",
    "startTime": "10:30",
    "endTime": "16:30",
    "days": [
      "SAT"
    ]
  }
]
```

Seems that it solves the problem. Maybe it is not as beautiful as it could be but it does represent all the information. And it kind of follows what we have for available assets per station - each asset type has its own entry. So maybe this is what we should stick with? Of course if there is a lot of stations and each has different opening times then that can explode into a lot of objects. Maybe we can solve that by adding a query parameter where you ask for opening hours only per given `stationId`? 

Probably you had an idea of how you would want to represent it so maybe let's get it here and then we can discuss.

**Comment by eborremans** [comment]
I was wondering how important it is for an MP to know about individual exceptions on operating hours? For instance, when you are closed on 25 dec should there be a way to make this known? Or does the planning-options endpoint (who then won't give an option for that date) suffice? I have been toying with the idea to return a calendar like so: replace the "days" field with 
`"operatingdays": [
      "date": "2020-01-14"
    ]`
But I am not sure about this. It would mean a TO would have to provide an entry for each day and a client would have to do quite some processing. I have also thought about default hours like suggested with the possibility of overrides. But this also seems to be to convoluted. 
Anyway, I am just mentioning it to be sure that MPs don't run into trouble when TOs are closed on exceptional dates that are not covered by the information in the operating hours endpoint.

**Comment by fhenryot** [comment]
As trip planner provider, let me insist on the importance to get opening hours at stations level. Whatever the dates/hours structure you propose, from my point of view it should come using one request to get an overview of possible pickup and dropoff for trip calculation.
I means to plan the journey but also during the follow in real time.

It's similar discussion about vehicle availabilities.
Thanks
Fabrice

**Comment by stephanroosli** [comment]
We have a concrete case here in Switzerland:
A TO (www.carvelo2go.ch) works with **private hosts** (they can be considered stations here) who each have one or more assets that they rent out. 
These are generally the same assets (e-cargobikes), but **each host defines it's own opening hours and days**. For example: Some public holidays or weekend days are restricted by some hosts and not by others, and opening hours are of course also different (some close at 6pm some at 8pm).

For an MP it must be possible to retrieve the "general opening times per station" in the /operator-information/ endpoint.
