### ISSUE TITLE
 [CHANGE REQUEST] There is no good `unitType` for `FIXED` FarePart types

### ISSUE THREAD

**Issue by canvural** [TOMP-WG/TOMP-API#304]
## API Version
1.0

## Summary
If we have `type` `FIXED` for a `FarePart` there is no good option for `unitType`. And it is a required field.

## Possible Solutions
I see 2 options:
- Make `unitType` not required. We can later clarify it in the Wiki or in the description. But this is not so good.
- Add a new enum to `unitType` Maybe called `FIXED`

**Comment by edwinvandenbelt** [comment]
third alternative: remove required from unitType

**Comment by canvural** [comment]
Yeah, that's the first option I wrote :smile:
