### ISSUE TITLE
[FEATURE REQUEST] Getting stations based on a location / Geojson

### ISSUE THREAD

**Issue by Tjalle** [TOMP-WG/TOMP-API#312]
## Is your feature request related to a problem? Please describe.

When trying to describe a station-based Mobility scheme, I'm struggling with getting the locations around a certain point.
In this particular case, I'm trying to get all possible assets (with availability) from (one or more) station(s) around a Mobility Hub.
The operator-information ( available assets) provides all the information, but I need a stationId to get only information on assets available neardby.
I would like a way to only get the stations within a provided geojson or lat/lon-range combo.

## Urgency
Minor : not a breaking feature, I am adding it as an amendment in my own documentation & implementation. But it would be good to keep the TOMP-API in line.

## Describe the solution you'd like

Preferably I'd like one of these two query param adaptations to the operator-information/stations endpoint : 

- a coordinates/radius combination as used in the plannings endpoint
- a geojson object in the query (cfr. the region result).

Query wise it seems easiest to take the first path.

This request would only return stations within the bounds provided.

## Describe alternatives you've considered
In the current setup, I would have to get all stations within a TO defined region (which I assume to be fairly large) and filter all results (also assumed to be a large number of stations, even within a citywide region) on the lat/lon every time.
This would be very resource-consuming and take away from the speed.
Another solution would be to do a full station request once and save the eligible stationIds locally in a database - this could lead to information that is not up to date.

**Comment by edwinvandenbelt** [comment]
Tjalle, this endpoint is actually provided for more or less static data... I've got the feeling you want to do some planning, by looking up nearby stations at a location (please call the /plannings endpoint for this purpose). Am I right? Or is there another scenario.

**Comment by edwinvandenbelt** [comment]
add extra filter options (query parameters): lon, lat, radius.
