### ISSUE TITLE
[CHANGE REQUEST] Clarification of documentation (question)

### ISSUE THREAD

**Issue by rolfchess** [TOMP-WG/TOMP-API#324]
## API Version
1.0.0 Dragonfly
Wiki page https://github.com/TOMP-WG/TOMP-API/wiki/Booking-phase#Default-booking-workflow
dated 16 Nov 2020

## Summary
Changing the state of a booking and the use of IDs is a bit confusing to us. As stated in the booking workflow on the [wiki](https://github.com/TOMP-WG/TOMP-API/wiki/Booking-phase#Default-booking-workflow),  the `/bookings` endoint is used to change the state of the booking. There are two things that are confusing:
1. In the wiki page, it states that the TO can commit legs when a client commits the booking. However, there is no "commit" state in a leg. In what state should the legs be after committing a booking?
2. During our conversation with the TOMP team, there was a suggestion that the id of the first leg shoud/could have the same id as the booking. Although it sounded like a handy "feature" at the time, it does bring up the question if the booking endpoint should react to leg id's (as: any leg Id in a booking can refer to a booking), and if so, would that mean that the booking will change state, or just that single leg?

For now, we assume that bookings and legs are separate entities, and all entities have globally unique id's in our system. That means that when passing in a leg id to the booking endpoint, the system will respond with a 404, as the id refers to a leg, and not a booking. Is this correct/expected/intended behavior?

**Comment by eborremans** [comment]
In any case I completely agree that bookings and legs are separate entities and that they should not intentionally share ids. In fact I would hope this holds for all entities. I.e. a planning option is not a reservation. Of course you could use an overlapping - lets say - transaction id, that would be fine, but the other entities should still have their own ids. Note, this is not in answer to your question, rather an opinion.

**Comment by edwinvandenbelt** [comment]
A booking and a leg are indeed seperate entities. In most cases, when a TO offers a booking, it is for 1 single leg (=the trip execution entity). But, the TOMP-API is of course only a description, not an implementation. The objects behind the API can be completely different from the objects in the API (actually, it is not very wise to make them 1:1, you could get problems when a new version is launched). But, your assumption is completely correct. If the IDs of bookings and the corresponding legs are not equal, you'll get a 404 when using the leg-id in a booking endpoint.

**Comment by rolfchess** [comment]
Thank you for the clarification, we will treat leg id's and booking id's as separate. (a leg id can not be used to fetch a booking).

Please note that although this is an API description, it *is* a contract, used to communicate real-world actions, events and state. It seems to me that it is important for all implementors to have a consistent detailed understanding of its meaning and how it reflects the different real world implementations.

**Comment by rolfchess** [comment]
I assume there are no plans to update the documentation on this, so I'll close the issue.
