### ISSUE TITLE
[CHANGE REQUEST] Add "CANCELLED" to legStates enum

### ISSUE THREAD

**Issue by rolfchess** [TOMP-WG/TOMP-API#325]
## API Version
1.0.0 Dragonfly
Wiki page https://github.com/TOMP-WG/TOMP-API/wiki/Booking-phase#Default-booking-workflow
dated 16 Nov 2020

## Summary
The booking endpoint implements a CANCEL event. The Mobility Provider is to call this endpoint when any of the other PTOs reject a booking. That means that a booking can in "PENDING" or "CONFIRMED" state when the MP cancels the booking. In the case of a confirmed booking, all leg states can be in state PREPARING or IN_USE, depending on the implementation of the PTO. In our case, leg state of a confirmed booking can be IN_USE, and contain tickets for the trip.

We are wondering what the leg state should be after cancelling a booking which was already committed.

**Comment by edwinvandenbelt** [comment]
Rolf, please take into account, that the TOMP-API specifies the communication, not the objects in your implementation. The leg object (or corresponding back office object) doesn't have to exist when the booking is confirmed or cancelled. It might be constructed when the first leg-endpoint is called. But if you want to use this object also in your backoffice, you're free to add extra states in this object (like 'NOT_YET_STARTED' and 'CANCELLED').

**Comment by rolfchess** [comment]
Edwin, in our case we have tickets when a booking is committed, which are immediately available to the client through the API. The tickets are returned as part of the Token in the Legs, and according to the TOMP API the Leg state is an enumeration of:
```
    legState:
      type: string
      description: status of a leg
      enum:
        [
          NOT_STARTED,
          PREPARING,
          IN_USE,
          PAUSED,
          FINISHING,
          FINISHED,
          ISSUE_REPORTED,
        ]
```

Freely adding states to this enumeration feels like a deviation from the specification where the client needs to know the specifics of each implementation.

Do I understand correctly that your answer implies that a booking can be cancelled at any time, and from that moment the client can no longer find the associated legs?

Maybe the leg state enum should have a CANCELLED state, that would make directly fetching the legs of a cancelled booking easier and clearer for both the client and the pto.

**Comment by rolfchess** [comment]
Can you please indicate if "CANCELLED" is to be added to the next API description so that it is part of the formal legState enum? Thanks in advance.

**Comment by edwinvandenbelt** [comment]
Ok. Let's add this state. It makes it possible to communicate about the cancelled legs as well.

**Comment by rolfchess** [comment]
Please note that to be complete, the enum in `legEvent` then also needs a "CANCEL" action.

**Comment by edwinvandenbelt** [comment]
This makes sense. It also provides the ability to cancel a (parallel) leg (e.g. having a parking lot, hotel room booked together.)
