### ISSUE TITLE
[BUG] The verb "ISSUE" in the legEvents is ambiguous

### ISSUE THREAD

**Issue by rolfchess** [TOMP-WG/TOMP-API#331]
In the enum "legEvent", there are currently the following values:

```
          enum:
            [
                PREPARE,
                ASSIGN_ASSET,
                SET_IN_USE,
                PAUSE,
                START_FINISHING,
                FINISH,
                ISSUE,
            ]
```

All words in this list are verbs, stated as operations on a leg. This would lead to believe that "ISSUE" means "To issue a Ticket" (which is very valid language for mobility providers who issue tickets).

If this is not the case, I propose that "ISSUE" is renamed to something verb-like as "REPORT_ISSUE" or maybe "REPORT_PROBLEM" to avoid the word "issue" all together.

**Comment by edwinvandenbelt** [comment]
Thanks Rolf! You're completely right. To be exact, the 'ISSUE' doesn't need to be there; the support module is there to handle this. In 1.2.0 this enumeration has changed: ISSUE is already removed.

**Comment by edwinvandenbelt** [comment]
Please close this issue.
