### ISSUE TITLE
Support passengers with wheelchairs

### ISSUE THREAD

**Issue by tom171296** [TOMP-WG/TOMP-API#336]
## Is your feature request related to a problem? Please describe.
Our TO would like to make a reservation with a wheelchair or something like that, but the current API doesn't rely documents how to do it. Is it already implemented?

## Urgency
Major

## Additional context
For our bus TO, there is a certain amount of wheelchair spots in the bus. The reservation system can take in count if the passenger is using a wheelchair. Our customer is asking the question if they can make a reservation for a passenger with a wheelchair.

## Describe the solution you'd like
In the plannings phase, there is a model used that contains requirements. For a passenger in a wheelchair, the requirement could be wheelchair spot. This is my current view on the requirements property, but I am not sure if that is the purpose of the property

![image](https://user-images.githubusercontent.com/12030148/109003113-543f9080-76a7-11eb-8134-d2d1f0d798dd.png)

**Comment by edwinvandenbelt** [comment]
Hello Tom, indeed, you're looking at the right spot. We use the "CROW reizigerswoordenboek" to communicate the standardized labels. It is not yet ready yet, the first version here: https://github.com/TOMP-WG/TOMP-API/blob/master/documents/Woordenboek%20Reizigerskenmerken%20CROW.pdf. In the current situation you should agree with your customer how to communicate this. Please send us your proposal as well, we can, in first instance, put it on the wiki. Later we can integrate it into the TOMP-API in a formalized way.

It could be something like this: "requirements": { "codes": ["HR01", "HR02"], "memo": "" }.

**Comment by edwinvandenbelt** [comment]
Maybe we should formalize this together, taking the "alignment first"-approach. Is often the cheapest way to do it.

**Comment by tom171296** [comment]
I would like to get in contact and see if we can formalize this together.
