### ISSUE TITLE
[FEATURE REQUEST] Cancel a leg

### ISSUE THREAD

**Issue by eborremans** [TOMP-WG/TOMP-API#337]
## Is your feature request related to a problem? Please describe.
Since authentication is not (yet) a part of TOMP, all parties currently seem to implement authentication based on bilateral agreements. We at Nazza, have chosen to work with accounts that are associated with roles. These roles determine the outcome of various TOMP calls. For instance, currently if an account with the USER role calls POST /bookings CANCEL, we can decide to incur a fee, whereas if a MAINTENANCE  role calls CANCEL, this does not apply. However, depending on the exact use case, even a MAINTENANCE account may want to CANCEL with a fee. TOMP could allow for distinguishing between these facilities by using separate calls for this. For instance CANCEL vs CANCEL_WITH_FEE.

The rationale behind this request is the following:
When end users are allowed to cancel bookings, a TO will typically associate bookings costs with it. This to prevent malicious users to book many assets and then cancelling them all as this can severely impact the asset availability for TOs.

I have also enclosed a state transition of the TOMP booking flow to indicate that there are several quite different ways to cancel a booking that TOMP can currently not differentiate between. This illustrates the context of our request.

![image](https://user-images.githubusercontent.com/9337704/110297436-c42d0f80-7ff3-11eb-9cd2-ebda01a70369.png)

## Urgency
major, for reasons described above

## Describe the solution you'd like
Because there are many aspects associated with this, this is something we probably have to discuss in WT 1 and WT 2 first.
- authentication & roles
- expiring vs releasing vs cancelling vs interrupting

## Describe alternatives you've considered
Like described above, we currently differentiate between various scenarios by using a role based model. However, this does not give us the flexibility needed.

## Possible Implementation
We could simply use additional events next to the CANCEL event: RELEASE, INTERRUPT, but I'd like to hear experience of how to deal with cancelling bookings from other TOMP members

**Comment by edwinvandenbelt** [comment]
Hello Eddy, the 'interrupted' event should be handled using 
a) the support endpoint in case of problems with the asset
b) the notifications endpoint (/bookings/{id}/notifications) with USER_NO_SHOW in case of a no-show of the traveler

But, in case of a decision from the MP side to cancel before the trip start (f.x. the previous leg delays), the /bookings/{id}/events must be called and it must be distinguishable to see who did it, or at least, if it should result in costs.

In most cases, the cancellation costs are dependent on a) time before departure and b) bilatural agreements between MP and TO. In these agreements the role of the cancelling party is often needed.

Proposal: extend the bookingOperation with a generic field 'origin', which can contain [MP, TO, END_USER, OTHER]. If obsolete, it should be considered as being the sending party. It can be overruled by the MP from MP-> END_USER or MP->OTHER and by the TO from TO->OTHER.
