### ISSUE TITLE
[FEATURE REQUEST] add "extraInfo" optional field to PlanningRequest (and other types)

### ISSUE THREAD

**Issue by rolfchess** [TOMP-WG/TOMP-API#346]
## Problem description
In the planning phase, we need a way for the client to provide us with additional information. This information is implementation specific, to be used during the planning phase and generation of tickets later on in the process.

In the `place` object there is an `extraInfo` object where arbitrary, implementation specific data can be stored. The `token` object has a similar construct with `tokenData`.

We'd like to see an `extraInfo` object in the `planningrequest` so that the client can provide us with this information without contaminating the TOMP specification with implementation specific details. Maybe it is a good idea to have a field like this in other objects too, so that MaaS providers and clients can provide a better service.

For instance, this could be used to indicate the type of wheelchair or required specific assistance, as requested in #336 (although wheelchairs, strollers, electric scooters might deserve/require a bit more than just some extra fields).

## Urgency
Critical (the TOMP API is not usable if this is not implemented), because we have situations where are not able to generate valid barcode tickets without the information passed in through the PlanningRequest/extraInfo.

## Proposed solution
Adding extraInfo to the PlanningRequest object would solve our immediate problem. Having this field as part of other objects, as currently in the `place` object might benefit other situtations.

## Considered alternatives
As the information is required during the creation of the booking/reservation, we would have to break with the TOMP API to be able to pass in the extra information. We see no logical alternatives.

**Comment by edwinvandenbelt** [comment]
Rolf, please contact me, I think we can manage most requirements already.

**Comment by edwinvandenbelt** [comment]
extraInfo as dictionary in bookingRequest & in customer to provide bilatural agreements.

**Comment by edwinvandenbelt** [comment]
bookingRequest:
      description: A booking requested by the MP
      type: object
      properties:
        id:
          description: A unique identifier for the TO to know this booking by
          type: string
        from:
          description: information about the origin, only to supply when requested in the conditionRequireBookingData
          allOf:
            - $ref: "#/components/schemas/place"
        to:
          description: information about the destination, only to supply when requested in the conditionRequireBookingData
          allOf:
            - $ref: "#/components/schemas/place"
        customer:
          description: The user that wants to make this booking, only to supply when requested in the conditionRequireBookingData
          allOf:
            - $ref: "#/components/schemas/customer"
        extraInfo:
          description: dictionary for extra fields (bilatural agreements)
          type: object
          additionalProperties: true

**Comment by edwinvandenbelt** [comment]
customer:
      description: A MaaS user that wishes to make a booking, only use the fields required by booking conditions
      allOf:
        - $ref: "#/components/schemas/traveler"
        - type: object
          required:
            - id
          properties:
            id:
              description: The identifier MaaS uses to identify the customer
              type: string
              example: "A0-123456"
            travelerReference:
              description: optional reference field to the travelers in the planning request.
              type: string
            initials:
              type: string
            firstName:
              description: First name of the customer
              type: string
              example: John
            lastName:
              description: Last name of the customer
              type: string
              example: Doe
            middleName:
              description: Middle name of the customer
              type: string
              example: von
            prefix:
              description: prefix of the customer, like titles
              type: string
            postfix:
              description: postfix of the customer, like titles
              type: string
            phones:
              type: array
              items:
                $ref: "#/components/schemas/phone"
            email:
              description: the email address of the customer
              type: string
            birthDate:
              type: string
              format: date
            address:
              $ref: "#/components/schemas/address"
            photo:
              description: base64 encoded
              type: string
              format: byte
            cards:
              type: array
              items:
                $ref: "#/components/schemas/card"
            licenses:
              type: array
              items:
                $ref: "#/components/schemas/license"
            extraInfo:
              description: dictionary for extra fields (bilatural agreements)
              type: object
              additionalProperties: true
