### ISSUE TITLE
[FEATURE REQUEST] Adding a healthcheck 

### ISSUE THREAD

**Issue by mhagendoorn-9292** [TOMP-WG/TOMP-API#352]
## Is your feature request related to a problem? Please describe.

Since TOMP can be used for core business, it would be nice to know if a provider I'm using is actually up and running correctly. To know this, I can submit a fake order every [x] minutes, but this doesn't really seem like a good idea to us (and [Microsoft](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-5.0)). To counter this issue, we (@jorismathijssen and me) would like to request a 'healthcheck' feature.

## Urgency

Major. We think that this can be a very valuable addition to TOMP, which can cause significant impact. 

## Additional context
Imagine you're starting a new company, which sole purpose is supplying commuters with rental bikes, cars and scooters. You're servering 100.000 people each month, generating €1.000.000 in revenue. On a windy afternoon, one of your partners that was supplying bikes has its servers blown into the North Sea. You continue renting out those bikes, because you didn't know his servers were down (and wet). Your customers get angry because they paid for a bike they never received, and you lose money because you have to reimburse them. 

## Describe the solution you'd like
The solution can be as simple as:

```
GET /ping
Response HTTP 200:
{
   "status": "ok"
}

Response HTTP 500:
{
   "status": "fail"
}
```

Or a little more complex:
```
GET /healthcheck
Response HTTP 200:
{
   "generalStatus": "ok",
   "buildVersion": "1.0.0",
   "buildDate": "2021-03-31T11:43:00Z",
   "environment": "Production",
   "healthChecks": [
      {
         "description": "External API",
         "status": "ok",
         "data": {},
         "responseTimeInMs": 0.32
      },
      {
         "description": "Database",
         "status": "ok",
         "data": {},
         "responseTimeInMs": 4.032
      } // etc..
   ] 
}

Response HTTP 500:
{
   "generalStatus": "fail",
   "buildVersion": "1.0.0",
   "buildDate": "2021-03-31T11:43:00Z",
   "environment": "Production",
   "healthChecks": [
      {
         "description": "External API",
         "status": "ok",
         "data": {},
         "responseTimeInMs": 0.32
      },
      {
         "description": "Database",
         "status": "fail",
         "data": {},
         "responseTimeInMs": 4.032
      } // etc..
   ] 
}
```
## Describe alternatives you've considered
Placing a fake order every [x] minutes to check if all systems are still functioning.

**Comment by edwinvandenbelt** [comment]
Hello Mike, next Wednesday morning we'll have a meeting. You'll be informed. Another way of working is calling the /operator/meta. This endpoint is the self-describing endpoint for the complete API. It doesn't say anything about the status of the service, except if it is running...

**Comment by mhagendoorn-9292** [comment]
Hi @edwinvandenbelt! Do you have a update regarding this issue? :)

**Comment by edwinvandenbelt** [comment]
Yes, absolute. The ticket is assigned and will be incorporated in v1.2.0, to be delivered at 1st of May.

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________
