### ISSUE TITLE
[FEATURE REQUEST] Helmets specification

### ISSUE THREAD

**Issue by robindboer** [TOMP-WG/TOMP-API#357]
## Is your feature request related to a problem? Please describe.
As a e-scooter (moped) sharing TO we have assets that require the traveler to wear a helmet. Currently no such field is part of the TOMP specification. I would like to request to make such field part of the assetProperties specification.

## Urgency
Minor, can currently be solved by making the helmet information available as part of the meta information.

## Describe the solution you'd like
I would like to suggest to add a `helmets` (integer) field part of the assetProperties schema.

## Describe alternatives you've considered
My current solution is to put this information in the assetProperties meta field.

**Comment by edwinvandenbelt** [comment]
This is already covered with the 'Ancillaries' in v.1.3.0. You can add, the traveler > requirements > abilities one of these:

SA-02	Helmet XS	Adult helmet XS
SA-03	Helmet S	Adult helmet S
SA-04	Helmet M	Adult helmet M
SA-05	Helmet L	Adult helmet L
SA-06	Helmet XL	Adult helmet XL
SA-07	Child Helmet S	Bike helmet S
SA-08	Child Helmet M	Bike helmet M
SA-09	Child Helmet L	Bike helmet L

**Comment by edwinvandenbelt** [comment]
The last remark is not complete. But in the 'assetProperties' there is nowadays a field 'helmetRequired'
