### ISSUE TITLE
[BUG] No category in journalEntry response

### ISSUE THREAD

**Issue by piotrj** [TOMP-WG/TOMP-API#362]
## API Version
1.1.0

## Summary
There is no `category` field in the response of `GET /payment/journal-entry` endpoint. If we assume that the amounts given in journal entry are always positive then there is no way to represent refunds in that endpoint (as opposed to `claim-extra-costs` web hook that allows to specify category0

**Comment by edwinvandenbelt** [comment]
There is a category in ExtraCosts. In the details of the journalEntry, there is OR a fare object OR an extraCosts object, containing the category. Is this what you're looking for?

**Comment by piotrj** [comment]
@edwinvandenbelt hmm, ok I guess I can use that. Although it's quite weird - since journal entries can be filtered by category and it seems that not all of them must have category (those that have fare instead of extra cost there won't).

**Comment by edwinvandenbelt** [comment]
Hmm. Should we add 'FARE' to the journalCategory? In addition to the current PR?

**Comment by piotrj** [comment]
@edwinvandenbelt yes I guess it would make sense to have it.
