### ISSUE TITLE
[CHANGE REQUEST] token data should have type property 

### ISSUE THREAD

**Issue by yamsergey** [TOMP-WG/TOMP-API#367]
## API Version
1.2.0

## Summary

[`Token`](https://app.swaggerhub.com/apis/TOMP-API-WG/transport-operator_maas_provider_api/1.2.0#/token) has `tokenData` field. The field can be on of type:
```
 TokenDefault"
 TokenDeeplink"
 TokenEKey"
 TokenQR"
 TokenEmpty"
```

When I use strong type language to implement to model, I have to have some kind of sign  which help me to decide which type is it. It's already done for [`condition`](https://app.swaggerhub.com/apis/TOMP-API-WG/transport-operator_maas_provider_api/1.2.0#/condition) which has `conditionType`.

## Expected Behavior
`TokenData` classes has required `tokenType` property.

## Current Behavior
`TokenData` classes don't have type

## Possible Solution
Add `tokenType`

**Comment by edwinvandenbelt** [comment]
Sergey, I guess you're completely right! We missed the 'discriminator'... I think this will result in a hot fix. I'll let you know!

**Comment by yamsergey** [comment]
😮  great news. Thank you 👍
