### ISSUE TITLE
[FEATURE REQUEST] license plate specification

### ISSUE THREAD

**Issue by matrover** [TOMP-WG/TOMP-API#368]
Is your feature request related to a problem? Please describe.
As an e-scooter (moped) sharing TO we have assets with an license plate and a name. the name field is misused for the license plate. I would like to request to make such field part of the assetProperties specification. so its standard for all MP's to use.

Urgency
Minor, currently the name field is misused

Describe the solution you'd like
I would like to suggest to add a license plate field part of the assetProperties schema.

Describe alternatives you've considered
My current solution is to put this information in the assetProperties meta field.

**Comment by edwinvandenbelt** [comment]
As discussed, we can add this field and enlist it on the wiki as possible 'GDPR'-violation fields.
