### ISSUE TITLE
[CHANGE REQUEST] AssetAccessData in Leg should be an array

### ISSUE THREAD

**Issue by yamsergey** [TOMP-WG/TOMP-API#371]
## API Version
1.2.0

## Summary
It's confusing when someone has to parse `assetAccessData` in `Leg`. [It's stated](https://app.swaggerhub.com/apis/TOMP-API-WG/transport-operator_maas_provider_api/1.2.0#/leg) that the value may be one of: `Token` or `TokenArray`, hence to work with it I have to check first what's inside. It's not that hard with JS, but if I use anything without native JSON supports it starts to be tricky.

## Expected Behavior
`assetAccessData` is just an array

## Current Behavior
`assetAccess` is on of:
            - $ref: "[#/components/schemas/token](https://app.swaggerhub.com/apis/TOMP-API-WG/transport-operator_maas_provider_api/1.2.0#/token)"
            - $ref: "[#/components/schemas/tokenArray](https://app.swaggerhub.com/apis/TOMP-API-WG/transport-operator_maas_provider_api/1.2.0#/tokenArray)"

**Comment by edwinvandenbelt** [comment]
Sergey, you're completely right, but we took this approach to stay backward compatible. Otherwise, we had to release a breaking version. And that's what we want to prevent.

**Comment by edwinvandenbelt** [comment]
Tomorrow we'll have a meeting with WT1. Could you please provide your snippet (proposal) in OpenAPI?

**Comment by yamsergey** [comment]
Unfortunately, I'm not that experienced in OpenAPI. Do you have any examples of how those proposals should be structured? The main idea is that this part:
```
        assetAccessData:
          description: Data to open a specific asset (e.g. QR code, image base64)
          oneOf:
            - $ref: "#/components/schemas/token"
            - $ref: "#/components/schemas/tokenArray" 
```

should become:
```
        assetAccessData:
          description: Data to open a specific asset (e.g. QR code, image base64)
          $ref: "#/components/schemas/tokenArray" 
```
