### ISSUE TITLE
[CHANGE REQUEST] to remove circular dependencies in Condition 

### ISSUE THREAD

**Issue by jeroenwijdemans** [TOMP-WG/TOMP-API#382]
## API Version
All API versions

## Summary
The Condition schemas has circular references. This makes it difficult to generate code from the YAML specs.

## Expected Behavior
No circular dependency while respecting the existing JSON input

## Current Behavior
Has circular dependency.
The Condition now has two concerns: it provides a list of possible conditions and it provides base fields as a subclass

## Possible Solution
Split the logic by adding a baseCondition element. This should allow the different conditions to have a single Parent. The Condition can then only list the Conditions while also adhering to the baeCondition

## Context (Environment)
Generating static code cannot handle circulair type references.

## Possible Implementation
I will submit a PR for the current version.

**Comment by edwinvandenbelt** [comment]
Hello Jeroen, WT1 is investigating your solution. We're going to decide next Wednesday how to approach if it's a patch release or is this something that can wait for 1.3.
