### ISSUE TITLE
[CHANGE REQUEST] - Optional asset related areas

### ISSUE THREAD

**Issue by m-witters** [TOMP-WG/TOMP-API#384]
## API Version
1.2.2

## Summary
There are transport operators that have additional conditionals to the geographical areas that can be used when using there asset. Areas that are prohibited, like shopping areas or nature. But also areas that are encouraged to be used, for example for advertising or logistical. The provider needs these areas to show and advice the traveller.  

## Expected Behavior
There is an element conditions part of the leg of the booking element (planning phase). 
Replace within the condition element the conditionReturnArea to something like conditionArea which contains a marker/id that tells how to use the area; PROHIBITED, RETURN, DISCOUNT(enum). 
Please also split the content of an area into a station and area object (oneof). The current content makes it possible to combine data, the remark is not used when generating code based on the yaml file. 

Consider using references within the TOMP messages. In this case, the areas are relative static and will be the same for multiple assets within the same region. Each asset will have the same large amounts of area data. Use within the asset a referenceId to the details of the area. The details of the area need to be described only once.

Consider moving conditions that are related to the asset, to the asset object. And make this information also available/part of the available-assets endpoint of the operator. Area information is related to the asset, not to the leg that is executed. Just like the need of a driving license. 

## Current Behavior
There is no possibility to communicate prohibited and/or discount areas.
To retrieve the available assets of the operator, the planning phase with booking-intent=false instead of the available-assets endpoint because not all data is supported and multiple requests need to be performed.

## Context (Environment)
For code generation, it would be nice if the TOMP specification prevents disruptions by defining and using objects instead of having a description that tells what is allowed. These descriptions can't be used when generating code and means that the implementation code needs to perform these checks.

It would be nice to normalise data within TOMP messages. Normalised data not only prevents possible mistakes, but also makes models more readable and reduces the size of the messages.

**Comment by edwinvandenbelt** [comment]
Small question: are the areas dependent on a booking? Or are they fixed for an operator? The solution you provide assumes there is a direct relationship between an area and a booking. For example, some bookings do have a DISCOUNT area and other don't. Is that the case? Otherwise, if the areas are only dependent on the operator, we could extend the 'region' endpoint with a type. This way of working allows also to communicate this data to journey planners.

**Comment by m-witters** [comment]
The areas are not fixed for an operator. Different assets of the operator can have different areas. The assets of the operator in Fx Amsterdam Noord can have other areas (like discount en return) then Fx Amsterdam Zuid and also different from Fx Alkmaar.
So I don't think the region endpoint is the correct endpoint. 

I also doubt about booking is the correct endpoint, because I think these areas are something that the traveller needs to known before starting the booking. 

I think it's all has to do with the word: available. Available from the point of view of an operator means that it can be used by someone, while available for the point of view of the traveller (could) mean, can I use the asset for the purpose I want to use it. Fx driving license needed and allowed to travel with the asset to locations are useful before starting the booking.

**Comment by m-witters** [comment]
Small remark, the areas are described as multipolygon by the GeoJson standard RFC 7946.

**Comment by m-witters** [comment]
Small remark, the areas are described as multipolygon by the GeoJson standard RFC 7946.
