### ISSUE TITLE
[CHANGE REQUEST] Specify the format for number fields to help code generators

### ISSUE THREAD

**Issue by jorismathijssen** [TOMP-WG/TOMP-API#400]
## API Version
1.2.2

## Summary
Swagger can be used in code generators. Some generators need the format field to be specified, so they know how to use a number field.

This is especially true for the AmountOfMoney object. Here a decimal is used for the amount field (good practice for money). But because the format field is not set to decimal, some generators generate a double for this field.

## Expected Behaviour
Specify the format field for the number field, so generators don't have to guess if they have to use a double or decimal.

## Current Behaviour
Some generators default to doubles. This is bad practice for fields that contain prices/currency.

## Possible Solution
Specify a ` format: decimal` or `format: double` line for every number field. Especially for the number fields that are related to currency. We should specify `format: decimal` here.

## Steps to Reproduce

1. Download the latest YAML file without the format: Decimal
2. Get latest version of NSwag Studio
3. Generate C# code with NSwag studio.
4. Generated code is with doubles instead of decimals

## Context (Environment)
We currently generate C# code based on the latest TOMP YAML file. 
Currently we have to specify this format field by hand but i think this will be a nice addition for everyone

## Detailed Description
``` yaml
amountOfMoney:
      type: object
      properties:
        amount:
          description: This should be in the base unit as defined by the ISO 4217 currency code with the appropriate number of decimal places and omitting the currency symbol. e.g. if the price is in US Dollars the price would be 9.95. This is inclusive VAT
          type: number
          example: 9.95
          format: decimal
        amountExVat:
          type: number
          example: 8.95
          format: decimal
        currencyCode:
          description: ISO 4217 currency code
          type: string
          minLength: 3
          maxLength: 3
        vatRate:
          type: number
          description: value added tax rate (percentage of amount)
          example: 21.0
          format: decimal
        vatCountryCode:
          $ref: "#/components/schemas/country"
```

**Comment by edwinvandenbelt** [comment]
Indeed, I agree. Can you make a pull request for this, or supply your altered YAML file?

**Comment by jorismathijssen** [comment]
Added a pull request. Also changed some field that, i think, should be integers. If this is not expected or maybe to big of a change for now, i will revert these changes.

**Comment by jorismathijssen** [comment]
Little note for this pull request:

OAS (Open Api Specification) did not define the decimal type as a possible data type. However they also state the following:

> Primitives have an optional modifier property: format. OAS uses several known formats to define in fine detail the data type being used. However, to support documentation needs, the format property is an open string-valued property, and can have any value. Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification. Types that are not accompanied by a format property follow the type definition in the JSON Schema. Tools that do not recognize a specific format MAY default back to the type alone, as if the format is not specified.

https://swagger.io/specification/#data-types

This can be scary. Especially the last sentence 

> Tools that do not recognize a specific format MAY default back to the type alone, as if the format is not specified.

I personally think that this is a problem for most of the, well known, tools. For example NSwag supports the decimal type. But i wanted to bring this to your attention @edwinvandenbelt, before this pull request is completed.

**Comment by edwinvandenbelt** [comment]
Thanks Joris! Personally, I don't think we can satisfy everyone and it's also a utopia to think we can make a solution that serves everyone in the best possible way. I think your contribution makes the API again a bit better and precise. Postprocessing will be needed in quite a few scenarios, after code generation.
