### ISSUE TITLE
TransportTypes 

### ISSUE THREAD

**Issue by skinkie** [TOMP-WG/TOMP-API#42]
What you are interested in:
 - https://github.com/NeTEx-CEN/NeTEx/blob/master/xsd/netex_framework/netex_reusableComponents/netex_mode_support.xsd#L80
 - https://github.com/VDVde/SIRI/blob/master/datex2/DATEXIISchema_1_0_1_0.xsd#L10042
 - TPEG_PTS proposal in SIRI 2.0

**Comment by efel85** [comment]
Added to list of links in repository. Still needs to be included in the code.

**Comment by pimmeh** [comment]
As requested by Roberto, an update whether this is needed for our 1.1 version or not.

I don't see an issue here, only extra information. So we don't need to address this in 1.1 I think?

**Comment by efel85** [comment]
Standarisation required between DatexII transporttypes and MaaS basecodetables from Accept.

**Comment by edwinvandenbelt** [comment]
adopt netex

**Comment by StevenHaveman** [comment]
We adopt netex because it also adopted on an EU level. Some background information here:

[National Access Points – getting closer to MaaS EU-wide.pdf](https://github.com/maas-nl/TOMP-API/files/3896391/National.Access.Points.getting.closer.to.MaaS.EU-wide.pdf)

**Comment by edwinvandenbelt** [comment]
the types in netex aren't complete. Their focus is on public transport. Bike and pedestrains f.i. are missing. I will search the the DATEX for an enum (other than a really small one), but in the TPEG_PTS proposal in SIRI 2.0 I cannot find one. It's a large document, but I think it's more about the infrastructure and again, PT.

**Comment by edwinvandenbelt** [comment]
Proposal: take our current enum, have a look at NETEX to complete it. After this, make the enum smaller and add an 'sub-class', making it possible to make the type more precise (e.g. 'BIKE' (enum) als class and 'cargo bike' as sub-class (free text)).

**Comment by skinkie** [comment]
> the types in netex aren't complete. Their focus is on public transport. Bike and pedestrains f.i. are missing. 

This is misinformation.
https://github.com/NeTEx-CEN/NeTEx/blob/master/xsd/netex_framework/netex_reusableComponents/netex_mode_support.xsd#L161

**Comment by edwinvandenbelt** [comment]
Sorry! You're right! I'll try to change it before Wednesday

**Comment by edwinvandenbelt** [comment]
This it should be (NeTeX, I removed ALL, UNKNOWN and added OTHER):
[AIR, BUS, TROLLEYBUS, TRAM, COACH, RAIL, INTERCITYRAIL, URBANRAIL, METRO, WATER, CABLEWAY, FUNICULAR, TAXI, SELFDRIVE, FOOT, BICYCLE, MOTORCYCLE, CAR, SHUTTLE, OTHER]. It's now in the API, including this:

     asset-sub-class:
          type: string
          description: a more precise classification of the asset, like 'cargo bike', 'public bus', 'coach bus', 'office bus', 'water taxi',  'segway', 'funicular'. This is mandatory when using 'OTHER' as class.


We had this one:
WALK, BIKE, MOPED, SCOOTER, STEP, CAR, TAXI, BUS, TRAM, LIGHTRAIL, METRO, TRAIN, FERRY, BOAT, AIRLINE, CABLEWAY, OTHER

If I had to setup one it would be the NeTeX without INTERCITYRAIL (=RAIL), URBANRAIL (=RAIL), CABLEWAY (=OTHER), FUNICULAR (=OTHER), TROLLEYBUS (=BUS), COACH (=BUS), SHUTTLE (=BUS) and SELFDRIVE (=can be anything). I would add something to support scooter and step.
