### ISSUE TITLE
[FEATURE REQUEST] Flight number

### ISSUE THREAD

**Issue by edwinvandenbelt** [TOMP-WG/TOMP-API#422]
## Is your feature request related to a problem? Please describe.
In the taxi domain, when picking up people at an airport, the flight number must be provided, otherwise, the taxi won't know where to go to collect the passengers.

## Urgency
Major: it's common in the taxi world to communicate this information.

## Describe the solution you'd like
in the planningRequest.from, there is the field 'stationId', but that would be a misusage. Putting it into from.physicallAddress.streetAddress also. 'Stopreference' is actually reserved for PT, .. An introduction of 'flightNumber' in from.extraInfo would help.

**Comment by markvandeven** [comment]
vouching for this. Flightnumber is most commonly used, but similar functionality would be needed if you are collecting a passenger from a ferry service or (international) train.
