### ISSUE TITLE
[BUG] Documentation: error code x203 is used twice

### ISSUE THREAD

**Issue by D3-Bug** [TOMP-WG/TOMP-API#429]
## API Version
Documentation

## Summary

[https://github.com/TOMP-WG/TOMP-API/wiki/Error-handling-in-TOMP](https://github.com/TOMP-WG/TOMP-API/wiki/Error-handling-in-TOMP)

<html>
<body>

Error code | Type | Example detail | Description
-- | -- | -- | --
x203 | Booking | Booking {} has started. | It is no longer possible to edit the details of this booking since the asset is already in use.
x203 | Booking | Booking {} not found. | The specified booking cannot be found.

</body>
</html>

Error code is the same for:
- not possible 
- not found

## Possible Solution
I think **not found** should be x204

**Comment by edwinvandenbelt** [comment]
Thanks! Changed it.
