### ISSUE TITLE
Missing response error codes.

### ISSUE THREAD

**Issue by MathieuRysk-IT** [TOMP-WG/TOMP-API#439]
**Is your feature request related to a problem? Please describe.**
Missing error codes on responses,

**429:** Too many requests. (for all responses)
**204:** Cancels a confirmed booking. Cancelling twice should still return 204.  (response of /bookings/{id}/events is missing in schema, older versions used to have this code?)

**Urgency**
Minor, we would like too add these ASAP tough.

**Describe the solution you'd like**
Simply add the error codes to the validation schema, i can do this manually but i rather keep myself to the schema supplied.

**Comment by edwinvandenbelt** [comment]
Hmmm. We didn't specify every errorcode in the specification.. It would let the specification explode. There are of course many valid error codes (408, 413, 423, 425, and so on) that could be applicable. You can add the response code anyhow.
What matters the 204 in /bookings/{id}/events, I think this should not be allowed. We'll remove it. After an event, you should be reported about the new state.
