### ISSUE TITLE
[CHANGE REQUEST] Add IDEAL as a payment method to the RentalMethods enum

### ISSUE THREAD

**Issue by jckastel** [TOMP-WG/TOMP-API#448]
The RentalMethods enum (used under /operator/stations) lists a variety of payment methods, but it is currently missing IDEAL. This should probably be added as an option.

**Comment by eborremans** [comment]
@WT1  I was wondering how TO payment methods are exactly relevant? I assume these payment methods are intended for end users. Payments between MP and TO are not taking place via these methods, are they? In addition, isn't the end user paying the Maas provider directly and via a payment method of the MPs choosing?

**Comment by edwinvandenbelt** [comment]
Proposal: introduced the field 'rentalMethodOther'. It can be used whenever in the 'rentalMethods' the method 'OTHER' is used. In the meantime, I also added 'cash' and 'bankcard'.
