### ISSUE TITLE
[FEATURE REQUEST] Notifications on leg

### ISSUE THREAD

**Issue by ruudrysk** [TOMP-WG/TOMP-API#450]
## Is your feature request related to a problem? Please describe.
Currently a notification during a leg will be submitted to the general booking, not a specific leg. (/bookings/{id}/notifications). When having multiple legs under a booking it should be possible to send ETA's and asset changes to a specific leg.  

Multiple types of /bookings/{id}/notification should be based on a leg, not on a booking. 
Examples: 
user_no_show is based on the traveler on a leg, not on a booking. 
vehicle_not_available is related to an asset on a leg, not the booking as multiple legs under a booking can contain different assets. 
ETA is based on a leg, as different legs can have different status. 

## Urgency
For registration with contract-based transportation the registration of specific actions on a specific leg is crucial, therefore we will set this future on critical.

**Comment by ruudrysk** [comment]
> Agree. What do you propose? An extra endpoint /legs/{id}/notification? Or an optional field with 'legId' in the body?

I would suggest extra endpoint /legs/{id}/notification

**Comment by edwinvandenbelt** [comment]
We agree that a simple endpoint should be the real solution, but for version 1.4 we propose a simple extension with 'legId' in the body of the booking notification. We duplicate this issue for version 2.0, since a new endpoint is a breaking issue.
