### ISSUE TITLE
swaggerhub specification of /payment/journal-entry in version 1.3.0 has incomplete category enum in query parameter

### ISSUE THREAD

**Issue by vmastenb** [TOMP-WG/TOMP-API#472]
## API Version
1.3.0

## Summary
swaggerhub specification of /payment/journal-entry in version 1.3.0 has incomplete category enum in query parameter
it is missing value 'fine'. It _is_ defined in the response-object.
![image](https://user-images.githubusercontent.com/4241856/199944198-c6ee552c-9bd0-4853-b301-fb3dc4c98346.png)

## Possible Solution
use the same object

**Comment by edwinvandenbelt** [comment]
Hmmm. I see 'FINE', just below 'REFUND'. But we can refer to the object journalCategory.
