### ISSUE TITLE
[FEATURE REQUEST] Make booking expiry time refreshable

### ISSUE THREAD

**Issue by eborremans** [TOMP-WG/TOMP-API#481]
## Is your feature request related to a problem? Please describe.
MaaS Providers often work with Payment Providers, where the payment process is handled outside of the context of the MaaS Provider client application. In those cases the MaaS Provider client will receive a callback from the Payment Provider once the payment transaction has completed. However, in practice there are many 'shopping cart' use cases and some of them can take quite long and the MP client cannot monitor the status of that process. Hence there is a serious risk that the TOMP booking phase 1 has timed out by the time the payment is completed. In that case the customer has paid for a booking that 
was not successful. This can somewhat be alleviated by setting the booking expiry sufficiently large, but this increases the likelihood of bad asset utilization in scenarios where customers often fail to proceed to the payment step.

In other cases, TO's want to increase the likelihood a product(booking), after it has been placed in the basket, to still be available at the moment of checkout. In these cases the client wants to be able to achieve an expiry time that is at least as large as the typical time a user needs to fill their shopping cart. I.e. while the user continues 'shopping' the client may decide to call refresh repeatedly. 

See picture below:
![image](https://user-images.githubusercontent.com/9337704/205028755-c0c57fe1-1365-482e-9b5f-19d63f2b354d.png)

## Urgency
Major - Asset utilization has a high priority while payment process issues are relatively
common.

## Describe the solution you'd like
If the booking expiry time can be refreshed, the efficiency can be improved. While 
the customer is executing the payment process, the MP client can refresh the booking
expiry time a limited nr of times until either the payment process completes (or is 
cancelled) or the maximum number of refreshes has been reached. The advantage of
this approach is that if the payment process fails early the booking spot can be released
early.

## Possible Implementation
2 new booking process identifiers:
- `ALLOW_REFRESH_TIMEOUT` - indicates that the TO supports refreshing the booking expiry time
- `MAX_NR_OF_REFRESHES : <value/>` - indicates the maximum nr of times the booking expiry time 
can be refreshed, if left out, the booking can be refreshed indefinitely, this is not advisable
- `MAX_REFRESH_INTERVAL : <value/>` - indicates the maximum size of the refresh interval. Note that the maximum PENDING time of a booking equals `[original expiry interval + (MAX_REFRESH_INTERVAL * MAX_NR_OF_REFRESHES)]`

The refresh can be implemented in the events endpoint with a new event REFRESH and two additional request fields:
```
POST /booking/{}/events REFRESH {
	operation: ...,
	origin": ...,
	refreshInterval : integer, -- refresh interval in milliseconds
	reason : [ORDER_PENDING, PAYMENT_PENDING, DEFAULT_INTERVAL_TOO_SHORT, OTHER] -- reason for refresh
}
```
or have its own endpoint

```
POST /booking/{}/refresh-pending {
	refreshInterval : integer, -- refresh interval in milliseconds
	reason : [ORDER_PENDING, PAYMENT_PENDING, DEFAULT_INTERVAL_TOO_SHORT, OTHER] -- reason for 
}
```

We as a TO would like to know the reason of the refresh if possible. Other reasons may be added.

In the resulting header the Expiry field should be updated with the changed expiry time. Note that if the client specified refresh interval is too large, it will be capped to the maximum allowed.

The booking flow would look like this:
![image](https://user-images.githubusercontent.com/9337704/205667124-e5dde0d0-8ca5-4ba6-8a39-5857b8c264c0.png)

**Comment by eborremans** [comment]
For this approach we'd also need a refresh interval size, or alternatively a maximum refresh interval size and an optional refresh_interval field in the booking events request so that the client can specify the desired refresh interval length. The response header should also return the new expiry time. I will update the proposal shortly

**Comment by edwinvandenbelt** [comment]
is it ok with you if we name it 'ALLOW_EXTEND_BOOKING_EXPIRY_TIME'?

**Comment by edwinvandenbelt** [comment]
The proposed solution is a bit different from yours: an extension can be requested (when the Process Identifier 'ALLOW_EXTEND_BOOKING_EXPIRY_TIME' is in place), and it can be granted or rejected. The MP is not allowed to request an expiry time, the TO should be in full control of it.

**Comment by eborremans** [comment]
> is it ok with you if we name it 'ALLOW_EXTEND_BOOKING_EXPIRY_TIME'?
You mean instead of `ALLOW_REFRESH_TIMEOUT`? That is fine with me.

**Comment by eborremans** [comment]
> The proposed solution is a bit different from yours

In my proposal the TO is in full control, we just provide some extra flexibility to the client regarding the desired refresh interval. As I documented earlier, if the client specified value is too large, it will be capped by the TO. Note however, that the client knows what suits their business case best. The added benefit is that the client has more freedom to tailor the specific value to their need as long as it is within the contraints provided by the TO.

**Comment by edwinvandenbelt** [comment]
The proposed solution is a little less complex. It just requests an extension of the expiry time, and it is granted or not.
________________________________
Van: eborremans ***@***.***>
Verzonden: vrijdag 9 juni 2023 13:26
Aan: TOMP-WG/TOMP-API ***@***.***>
CC: Edwin van den Belt ***@***.***>; Assign ***@***.***>
Onderwerp: Re: [TOMP-WG/TOMP-API] [FEATURE REQUEST] Make booking expiry time refreshable (Issue #481)


The proposed solution is a bit different from yours

In my proposal the TO is in full control, we just provide some extra flexibility to the client regarding the desired refresh interval. As I documented earlier, if the client specified value is too large, it will be capped by the TO. Note however, that the client knows what suits their business case best. The added benefit is that the client has more freedom to tailor the specific value to their need as long as it is within the contraints provided by the TO.
