### ISSUE TITLE
[FEATURE REQUEST] Add process identifier for required location in leg event

### ISSUE THREAD

**Issue by SvenDub** [TOMP-WG/TOMP-API#482]
## Is your feature request related to a problem? Please describe.
The `/legs/{id}/events` has an optional `asset.overridenProperties.location` property, we would like a way to indicate that this is required for our API.

## Urgency
Minor, the API works but the required property has to be communicated outside the spec, hindering discovery.

## Describe the solution you'd like
Required properties could be described using the process identifiers on the operator endpoint.

## Possible Implementation
Add a Trip Execution process identifier:
* `LOCATION_REQUIRED`: The TO requires a location to be sent with an event.

**Comment by edwinvandenbelt** [comment]
we could indeed add the process identifier 'LEG_EVENT_LOCATION_REQUIRED'. We'll discuss it in the next WT1 meeting.

**Comment by edwinvandenbelt** [comment]
We added this text in the process identifiers. It is a bit different (fine-grained) than the first solution, we have to deal with the traceability of personals (GDPR/AVG).

in some cases, the location is required in the leg events. We have added these process identifiers to cope with it:
LEG_EVENT_LOCATION_REQUIRED_SET_IN_USE: the location must be supplied when starting the leg
LEG_EVENT_LOCATION_REQUIRED_PAUSE: the location must be supplied when pausing the leg
LEG_EVENT_LOCATION_REQUIRED_OPEN_TRUNK: the location must be supplied when the trunk (/helmet box) is opened
LEG_EVENT_LOCATION_REQUIRED_FINISH: the location must be supplied when the leg is ended
LEG_EVENT_LOCATION_REQUIRED_TIME_EXTEND: the location must be supplied when the leg is extended in time (whenever possible of the asset)
LEG_EVENT_LOCATION_REQUIRED_ASSIGN_ASSET: the location must be supplied when assigning an asset
There is no generic LEG_EVENT_LOCATION_REQUIRED process identifier: you have to be aware of what you are requesting. Sharing this information requires a need to share it (GDPR).
