### ISSUE TITLE
Availability of historical logging between MSP and TO

### ISSUE THREAD

**Issue by efel85** [TOMP-WG/TOMP-API#50]
Discussed during meeting on 21/8:

@eborremans brought forward the risk of possible malicious intent during the booking process. @skinkie  added that this brings forward the discussion about the need for historical logging. Who is going to log what? Can a MSP retrieve historical logging on all transactions from a TO? Pim suggested the currently described GET-call for booking transactions does not specify a time range, so in theory all transactions with a certain booking state can be retrieved. 

This issue needs to be addressed during later development stages, first focus is to get things up and running in the first place.

**Comment by efel85** [comment]
Has a link with the invoicing process. Certain logs would need to be kept until invoicing and payment is approved and completed. They can be removed afterwards. 
Bigger discussion required on ownership of data and levels of aggregation allowed to retain data.

**Comment by edwinvandenbelt** [comment]
We decided to close this one.
