### ISSUE TITLE
First ideas for payment facilities

### ISSUE THREAD

**Issue by efel85** [TOMP-WG/TOMP-API#69]
During the TOMP-API meeting on 30 October, the following first ideas for payment facilities in the TOMP-API were discussed:

**First assumptions:**

1. we should re-use or find complementarity with existing payment facilities, we should not re-invent the wheel
2. we need to understand how existing payment schemes work to understand how the TOMP-API can function in relation to these schemes.
3. the basis for every payment transaction is an underlying B2B-contract between parties. This is not part of the TOMP-API scope. The API should only facilitate the information exchange necessary to fulfil the contract stipulations.
4. how the user pays the MSP is up to the MSP and not in scope for the TOMP-API. The payment scope in the TOMP-API is always between MSPs and TOs.

**First ideas:**

1. at the end of each leg (or trip), usage statistics need to be exchanged, reconciled and acknowledged between MSP and TO as a basis for a (future) payment transaction. 
2. payment between MSPs and TOs will always be based on a contract and invoicing period. The contract reference and invoicing period can be part of the reconciliation call within the TOMP-API. 
3. A payment transaction between MSP and TO does not necessarily have to take place on-the-fly, but can be delayed to weekly/monthly/quarterly etc. depending on contract.
4. introduce payment states in TOMP-API to exchange status of payment for each leg. This enables a look-up service for MSPs to understand which payments are due within which period. These payment states can be delivered as line-items referring to a specific booking and/or booking state.
5. introduce confirmation of the subscription model between MSP to TO with verification. E.g. a senior citizen uses a MaaS-app and has a right to discounted tickets. This should be communicated (and verified to prevent fraud) between MSP and TO in the planning phase, also to calculate expected costs of a trip.

**Comment by edwinvandenbelt** [comment]
replaced by #75

**Comment by edwinvandenbelt** [comment]
in the payment module there should be an endpoint to directly request payment. Please add (in claim-extra-costs):
    post:
      tags:
        - payment
        - MSP
      description: the TO can request a direct transfer of money in case of deposits or rentable valuable asset
      parameters:
        - name: id
          in: path
          description: leg id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/journal-entry'
      responses:
        '200':
          description: money has been transferred to TO
          headers:
            'Content-Language':
              description: ISO 639-1 two letter language code
              example: nl
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/journal-entry'
        '201':
          description: journal entry received, will be processed (state = INVOICED)
          headers:
            'Content-Language':
              description: ISO 639-1 two letter language code
              example: nl
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/journal-entry'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'

**Comment by edwinvandenbelt** [comment]
except for the 'claim extra costs'
