### ISSUE TITLE
New booking scenario: Postponed commitment

### ISSUE THREAD

**Issue by edwinvandenbelt** [TOMP-WG/TOMP-API#72]
SwiftFare is a platform between real TO's and the MSP, acting like a TO. But they cannot give directly a 'COMMIT', they have to ask their 'subTO's' and that's not within seconds.

possible solutions:
a) do commit and cancel when a subTO rejects,
b) create another state 'partially committed', but what to do with the payments/supplied tickets etc
c) only allow this TO (with his subTO's) on single leg trips
d) propose the conditions upfront to the end user and let the risks (and costs) be part of his/her decision.

**Comment by StevenHaveman** [comment]
Good suggestion! This "broker" business model is something that the TO-MP API should definitely support. For my understanding - is this currently limited? I can't find that limitation right now. e.g. not here (https://github.com/maas-nl/TOMP-API/wiki/Booking-phase)

**Comment by edwinvandenbelt** [comment]
@Tjalle and Roberto, at the moment I've added an extra state, an extra event (deny) and a condition in the planning option. Please have a look before Wednesday
