### ISSUE TITLE
A high-level roadmap for TO-MP API developments

### ISSUE THREAD

**Issue by StevenHaveman** [TOMP-WG/TOMP-API#79]
In discussion with Ross we came to the conclusion that it would be beneficial to have a sort of roadmap that shows our development ideas (visually) and also shows for example data sharing standardization efforts that are at least considering and might be undertaking.

**Comment by edwinvandenbelt** [comment]
Items to put on the roadmap:
- proof of the pudding 
- certification 
- review static information 
- future support of API
- described scenarios
- (nl only) mapping to TNO learning environment 
- GS1?

**Comment by edwinvandenbelt** [comment]
extra scenarios like vouchers (payment), return areas (system info), conditions (planning/booking), thirth party payment (payment)

**Comment by edwinvandenbelt** [comment]
supportive tooling (e.g. extend opentripplanner)

**Comment by edwinvandenbelt** [comment]
it's missing now the ability to inform -like gbfs- the amount of available assets.
