### ISSUE TITLE
Rename maas-nl to be tompwg

### ISSUE THREAD

**Issue by ro5k0** [TOMP-WG/TOMP-API#84]
Can I suggest we rename the community name from maas-nl to be tompwg to reflect our broader EU approach.

**Comment by ro5k0** [comment]
https://github.com/maas-nl --> https://github.com/tompwg

**Comment by edwinvandenbelt** [comment]
is already on the action list, Edoardo is already asked.

**Comment by bonbakermans** [comment]
Done.
