### ISSUE TITLE
Extra parameters in the POST bookings/id call

### ISSUE THREAD

**Issue by kushshr** [TOMP-WG/TOMP-API#97]
A TO might want some more fields in the bookings call (e-mail, personal address and date of birth) etc. We might also need to add a field like pickup address in case of a taxi, where the driver just knows the lat/long and not the exact address where they need to pickup.

**Comment by edwinvandenbelt** [comment]
See also #94.

**Comment by edwinvandenbelt** [comment]
in 1.1.2
